### ISSUE TITLE
SVN, Github mirrors - Stable branch?

### ISSUE THREAD

**Issue by Dav1dde** [KhronosGroup/OpenGL-Registry#10]
I am the developer of [glad](https://github.com/Dav1dde/glad) and currently in glad the [SVN/CVS](https://cvs.khronos.org/svn/repos/ogl/trunk/doc/registry/public/api/) will be used to download specifications (as well as for daily updates on the online generator).

Now with https://github.com/Dav1dde/glad/issues/73 the issue arose of a bug in the spec, you guys fixed the issue very quickly here, but this fix has not been pushed to SVN yet. 

What is the state of the SVN mirror? Is the Github master branch "stable enough" to use?

**Comment by oddhack** [comment]
SVN is no longer being maintained. If it will help make that clear I'll add a couple of README files in places you suggest. We can't really get rid of it since it will instantly break projects such as yours, but we can try to make it more clear that it is falling out of date.

**Comment by Dav1dde** [comment]
Alright thanks for the clarification, I will update all links to use Github.
