### ISSUE TITLE
Macro GL_BLEND_COLOR not "required"

### ISSUE THREAD

**Issue by ferreiradaselva** [KhronosGroup/OpenGL-Registry#103]
This is related with the issue https://github.com/Dav1dde/glad/issues/115.

I'm using [glad](https://github.com/Dav1dde/glad) loader, with OpenGL core 3.3, and it seems that the loader doesn't define `GL_BLEND_COLOR` because in the `gl.xml`, `GL_BLEND_COLOR` is not `<require>`'d by GL 2.0.

However, the functions `glBlendColor`, `glBlendFunc`, `glBlendEquation` are available for OpenGL 2.0-4.5, and assume that you can use `GL_BLEND_COLOR`.

Am I mistaking something or is it an actual bug?

**Comment by oddhack** [comment]
I think that's a good catch, though I'm not actually going to go all the way back to 15 year old emails to verify what our reasoning was at the time, which I TBH don't remember :-) Added BLEND_EQUATION and BLEND_COLOR to GL 1.4 core feature interfaces in gl.xml, in #104 - let me know if that helps.

**Comment by oddhack** [comment]
Closed by #104.
