### ISSUE TITLE
Program interface query doesn't talk about subroutine queries.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#11]
In 7.3.1 of OpenGL 4.5, when explaining the behavior of `glGetProgramResource`, the behavior of the properties `GL_NUM_COMPATIBLE_SUBROUTINES` and `GL_COMPATIBLE_SUBROUTINES` are never explained. This also causes a problem with the subroutine introspection APIs added to 4.0, since they are now defined in terms of the behavior of those two properties. Which are not described.

**Comment by pdaniell-nv** [comment]
This is being tracked internally in opengl/API/issues/40.

**Comment by oddhack** [comment]
This has been fixed in the next ES / GL spec drafts, which will be coming out shortly.
