### ISSUE TITLE
gl.xml: glBlendColor/glBlendEquation introduced in GL 1.2.1 spec, but only in 1.4 spec in the xml

### ISSUE THREAD

**Issue by null77** [KhronosGroup/OpenGL-Registry#118]
Looking at the GL 1.2.1 spec:

https://www.khronos.org/registry/OpenGL/specs/gl/glspec121.pdf

It seems these two functions are present (and associated enums). But in latest gl.xml it seems they're recorded as being introduced in GL 1.4.  Although it's highly unlikely to matter in practice, this difference seems like a technical error likely in the xml.

@oddhack any thoughts?

**Comment by oddhack** [comment]
They were part of the optional ARB_imaging extension until GL 1.4, then made part of the mandatory core features, which is why it's expressed that way.
