### ISSUE TITLE
undefined GL_NUM_DEVICE_UUIDS enum appearing in pname group

### ISSUE THREAD

**Issue by keriharris** [KhronosGroup/OpenGL-Registry#125]
In gl.xml the "pname" group references GL_NUM_DEVICE_UUIDS:

        <group name="GetPName">
            ...
            <enum name="GL_NUM_DEVICE_UUIDS"/>

GL_NUM_DEVICE_UUIDS is not mentioned anywhere else in the document.
GL_NUM_DEVICE_UUIDS_EXT on the other hand is defined:

         <enum value="0x9596" name="GL_NUM_DEVICE_UUIDS_EXT"/>

**Comment by dgkoch** [comment]
It should be GL_NUM_DEVICE_UUIDS_EXT. 

@keriharris Would you like to make a pull request?
