### ISSUE TITLE
BlendingFactor group contains duplicate entries

### ISSUE THREAD

**Issue by keriharris** [KhronosGroup/OpenGL-Registry#126]
The BlendingFactor group contains two duplicate enums:

`        <group name="BlendingFactor">
            <enum name="GL_ZERO"/>
            <enum name="GL_ONE"/>
            <enum name="GL_SRC_COLOR"/>
**1         <enum name="GL_ONE_MINUS_SRC_COLOR"/>
            <enum name="GL_DST_COLOR"/>
            <enum name="GL_ONE_MINUS_DST_COLOR"/>
            <enum name="GL_SRC_ALPHA"/>
**2         <enum name="GL_ONE_MINUS_SRC_ALPHA"/>
            <enum name="GL_DST_ALPHA"/>
            <enum name="GL_ONE_MINUS_DST_ALPHA"/>
            <enum name="GL_CONSTANT_COLOR"/>
            <enum name="GL_ONE_MINUS_CONSTANT_COLOR"/>
            <enum name="GL_CONSTANT_ALPHA"/>
            <enum name="GL_ONE_MINUS_CONSTANT_ALPHA"/>
            <enum name="GL_SRC_ALPHA_SATURATE"/>
            <enum name="GL_SRC1_COLOR"/>
**1         <enum name="GL_ONE_MINUS_SRC_COLOR"/>
            <enum name="GL_SRC1_ALPHA"/>
**2         <enum name="GL_ONE_MINUS_SRC_ALPHA"/>
        </group>
`

Based on the glBlendFunc documentation [1], I'm guessing that the duplicate entries should be GL_ONE_MINUS_SRC1_COLOR and GL_ONE_MINUS_SRC1_ALPHA respectively.

[1] https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml

**Comment by pdaniell-nv** [comment]
@keriharris can you propose a pull request to fix this? Thanks.
