### ISSUE TITLE
Split opengl 1.1 and opengl 1.0 enums

### ISSUE THREAD

**Issue by mdsitton** [KhronosGroup/OpenGL-Registry#13]
Currently many of the opengl 1.0 enums are included with the opengl 1.1 enums. There is a comment mentioning this in the xml, but i'd like to see this fixed.

**Comment by oddhack** [comment]
You are welcome to propose a PR doing this. It's a nuisance to even *find* a GL 1.0 header file at this point.

**Comment by mdsitton** [comment]
Well I actually did track one down a few months ago and created a list of gl 1.0 enums for my project so I may do a pr if i get the time.

**Comment by mdsitton** [comment]
So i actually just wrote a quick python script to separate them out based on the list i had so it was fairly simple. Pull request submitted #14
