### ISSUE TITLE
DispatchComputeIndirect error list in GL 4.5

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#15]
The error list `DispatchComputeIndirect` says:

> An INVALID_OPERATION error is generated if zero is bound to the
DRAW_INDIRECT_BUFFER binding.

I'm fairly sure that should be `DISPATCH_INDIRECT_BUFFER`, not _`DRAW`_.

**Comment by oddhack** [comment]
This has been fixed for both ES and GL in the next spec updates, coming shortly.
