### ISSUE TITLE
Validity testing for binding points

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#16]
Note that this bug was taken from [the Bugzilla database](https://www.khronos.org/bugzilla/show_bug.cgi?id=1448). There was a response that indicated that this would be discussed and corrected, but new versions of the specification were published since then, and the issue remains.

----

There are several scenarios that the OpenGL specification does not explicitly disallow which are... dubious. For example:

````
layout(binding = 0, r32ui) uniform uimage2D foo;
layout(binding = 0, r32ui) uniform uimageRect bar;
````

The validation rules in section 11.1.3.11 explicitly disallows this for samplers, but *not* for images. And there is no explicit disallowing of two image types from using the same binding index. Which also means:

````
layout(binding = 0, r32ui) uniform uimage2D foo;
layout(binding = 0, r32f) uniform uimage2D bar;
````

The same image unit is being used with different formats.

This extends to other things as well. There is no language explicitly disallowing the user from having UBO/SSBO's share the same binding index. So this is technically legal:

````
layout(std430, binding = 0) buffer Buff1{...};
layout(std430, binding = 0) buffer Buff2{...};
````

Now, the behavior of accessing the same memory through different buffer variables is well understood (memory coherency is only guaranteed by default for read/writes to memory through the same variable). So such code could theoretically work.

But what does it mean if `Buff1` and `Buff2` are declared differently?

Is the ability to do these things an oversight or is it intended for them to be allowed?

**Comment by oddhack** [comment]
I pinged JohnK on the bugzilla. FYI, this repository isn't the right place for API and spec bugs. We'll probably setup some empty language / API repos soon for that purpose, since we get a lot more engagement internally on Github than on public bugzilla - but this is just the registry, not the place where the WGs operate.
