### ISSUE TITLE
Need better type dependency mechanism in XML specs

### ISSUE THREAD

**Issue by nicebyte** [KhronosGroup/OpenGL-Registry#160]
The "type" element may have a "requires" attribute, which allows one to specify a type that a given type is dependent on. This allows type elements to be processed in arbitrary order while still guaranteeing correctness of generated code.

However, this mechanism does not work when more than a single type is required.

Case in point: GLDEBUGPROC.

GLDEBUGPROC is defined as:
`
typedef void ( * GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,const void *userParam);`

It relies on a number of other non-builtin types. The corresponding type element lacks a "requires" attribute, and there's no way to determine its dependencies short of parsing the C typedef declaration.

As long as the tool that consumes the XML spec processes all types in the order they appear in the file, this won't present an issue. However, if for some reason things go in incorrect order, errors may occur.

Proposed fix: surround the referenced non-builtin types with <ptype> tags, as is already done for command parameters and return values.

Using this rule, the new type element for GLDEBUGPROC would look like:
`
<type>typedef void ( * <name>GLDEBUGPROC</name>)(<ptype>GLenum</ptype> source, <ptype>GLenum</ptype> type,<ptype>GLuint</ptype> id, <ptype>GLenum</ptype> severity, <ptype>GLsizei</ptype> length,const <ptype>GLchar</ptype> *message,const void *userParam)</type>`

**Comment by oddhack** [comment]
At some point in the not too distant future, I hope to migrate gl.xml and scripts over to the slightly different and more up-to-date schema and scripts used by Vulkan, which does support these additional type dependencies. Until and unless it turns into a severe problem, though, I'm unlikely to put any effort in to backport portions of those changes to the current GL schema.

Realistically speaking, the only types required by the callbacks are basic GL types used by hundreds of other commands, and are going to be defined by all OpenGL headers. So while I acknowledge there's a theoretical problem, it isn't a priority.

I don't know how to label something "known fix that will be dealt with later at larger scope" so am just going to close this wontfix, although that's not exactly true.
