### ISSUE TITLE
gl.xml Missing "len" values in disjoint-timer-query and robustness extension functions

### ISSUE THREAD

**Issue by B1m0** [KhronosGroup/OpenGL-Registry#164]
I am using the gl.xml for CodeGeneration with glad and i noticed that the len value on some parameters are missing. For example the glGetnUniformfv is missing the len value on "params" while glGetnUniformfvARB and glGetnUniformfvEXT got them.

Following a list of functions where the value is missing
- glReadnPixels - `<param>void *<name>data</name></param>`
- glGetnUniformfv - `<param><ptype>GLfloat</ptype> *<name>params</name></param>`
- glGetnUniformiv - `<param><ptype>GLint</ptype> *<name>params</name></param>`
- glGetnUniformuiv - `<param><ptype>GLuint</ptype> *<name>params</name></param>`
- glGetnUniformfvKHR - `<param><ptype>GLfloat</ptype> *<name>params</name></param>`
- glGetnUniformivKHR - `<param><ptype>GLint</ptype> *<name>params</name></param>`
- glGetnUniformuivKHR - `<param><ptype>GLuint</ptype> *<name>params</name></param>`
- glGetQueryivEXT - `<param><ptype>GLint</ptype> *<name>params</name></param>`
- glGetQueryObjectivEXT - `<param><ptype>GLint</ptype> *<name>params</name></param>`
- glGetQueryObjectuivEXT - `<param><ptype>GLuint</ptype> *<name>params</name></param>`

**Comment by pdaniell-nv** [comment]
Looks like you're right. Are you planning to create a PR for this? It would be appreciated.
