### ISSUE TITLE
Extra or omitted text in Program Objects section of GL 4.6 Spec

### ISSUE THREAD

**Issue by nanley** [KhronosGroup/OpenGL-Registry#182]
On page 97 of the spec, you can find the words "The command" floating between two sentences:

> If UseProgram is called with program set to zero, then there is no current program object.
The command
The executable code for an individual shader stage is taken from the current program for that stage.

**Comment by oddhack** [comment]
Thanks. I've fixed this internally and it will show up the next time we do a public spec update (which may be a while).
