### ISSUE TITLE
gl.xml: GL_TEXTURE_LUMINANCE_TYPE and GL_TEXTURE_INTENSITY_TYPE required in `compatibility` profile, later removed from `core`

### ISSUE THREAD

**Issue by Rijenkii** [KhronosGroup/OpenGL-Registry#189]
In gl.xml, enums `GL_TEXTURE_LUMINANCE_TYPE` and `GL_TEXTURE_INTENSITY_TYPE` are required in 3.0 for `profile="compatibility"` (line 33935), and later removed in the version 3.2 BUT for `profile="core"` (line 34980).
Is it intended?

**Comment by oddhack** [comment]
Yes, that's intended. The core profile introduced in OpenGL 3.2 does not support luminance and intensity formats.

**Comment by Rijenkii** [comment]
Wait, but why then in 3.0 these enums are added for `profile="compatibility"`, but, according to a comment in gl.xml, core and compatibility profiles were first introduced in 3.2?

**Comment by oddhack** [comment]
TBH, I don't recall this many years later. There was probably some reason motivated by a combination of the generator scripts and the schema limitations. If you're concerned about this you could propose an XML change, but it would have to have no semantic impact on the current header files to be accepted.

**Comment by Rijenkii** [comment]
Also, was `GL_INDEX` also removed from core? Because it is added in the same require block as already mentioned enums, but not removed from core. (Last question, promise (probably))

**Comment by Rijenkii** [comment]
Yep, found it
