### ISSUE TITLE
Missing extensions WGL_AMDX_gpu_association and WGL_ATI_render_texture_rectangle

### ISSUE THREAD

**Issue by SilverPhoenix99** [KhronosGroup/OpenGL-Registry#192]
When I grab the extensions string on my PC I get back these 2 extensions, but I can't find them in the `wgl.xml` spec.

Both the `WGL_AMDX_gpu_association` and the `WGL_NV_render_texture_rectangle` extensions exist in the same spec.

Are they missing, or were they not added for some particular reason I'm not aware?

Thanks in advance.

**Comment by oddhack** [comment]
We do have a spec for the NV extension so I'll add that to the registry / headers soon - was overlooked for some reason. The spec is 15 years old and this is the first time I recall someone mentioning it. The AMDX extension is unknown to us, but is probably an early version of the WGL_AMD_gpu_association, which is in the registry.

**Comment by oddhack** [comment]
Actually, WGL_NV_render_texture_rectangle is already in the registry (and generated wglext.h):

https://github.com/KhronosGroup/OpenGL-Registry/blob/master/xml/wgl.xml#L1915-L1921

So, I don't think there's anything left to do here. If the AMDX extension specification gets posted by AMD, I will add it to the registry - maybe you could ask their developer support people about it.

**Comment by SilverPhoenix99** [comment]
Hi @oddhack 

I also found the NV one in the registry, but the extension WGL_ATI_render_texture_rectangle is ATI not NV. I would assume they serve the same function, but they seem have different enumerations (no functions). It looks like the Glew project has it defined, which makes me wonder where they got it from. If you could have a second look at this, I'd appreciate it.

WGL_AMD_gpu_association is from 2009, but the GPU is recent (RX 580), and AMDX was for non-finalized (or WIP) specs, iirc. Maybe it's included by default for backwards-compatibility since both the AMD and the AMDX extensions exist on this GPU.

Thanks again.

**Comment by oddhack** [comment]
I was looking at the issue body and not the title. Sorry about that. Unfortunately, the answer is the same for both of them - if I don't have an extension specification, I have no basis to include it in the XML/header. I will pass on a request to someone from AMD in Khronos to look for specs, but judging by Google search results, they've never published them. GLEW apparently added them at one point but I have no idea what they based that on.

**Comment by NeilMonday** [comment]
Is there any problem with an implementation reporting an extension that does not exist in wgl.xml?

If the list of reported extensions must match what exists in wgl.xml, then I can do the following:
1. WGL_AMDX_gpu_association is exactly the same as WGL_AMD_gpu_association. I think I will go ahead and remove the AMDX version from our driver. 
2. I found the old WGL_ATI_render_texture_rectangle extension. It seems to be a subset of the NV one, but it does have a few differences like the enum value. So it would probably be best to upload it I think.

**Comment by oddhack** [comment]
@NeilMonday thanks for following up so fast. There's no requirement that you register extensions, but it's helpful for developers for the registry to be complete, since that's where they look for documentation (as seen in this issue). I'd appreciate it if you're able to submit the ATI extension spec to the registry - you could just attach it to this issue.

**Comment by pdaniell-nv** [comment]
@NeilMonday are you planning to register these extensions? Just wondering if we can resolve this issue. Thanks.

**Comment by NeilMonday** [comment]
Thanks for the reminder, and sorry for the delay. Here is what we have for WGL_ATI_render_texture_rectangle.

[WGL_ATI_render_texture_rectangle.txt](https://github.com/KhronosGroup/OpenGL-Registry/files/2311785/WGL_ATI_render_texture_rectangle.txt)

**Comment by oddhack** [comment]
I think the only remaining action here is to publish WGL_ATI_render_texture_rectangle in the registry, which I'll do soon.

**Comment by oddhack** [comment]
Done. Amusingly there is reuse of the WGL enum value for two unrelated AMD/ATI purposes. We'll likely never know why.
