### ISSUE TITLE
Wrong enum group for glGetIntegeri_v and glGetInteger64i_v argument

### ISSUE THREAD

**Issue by joonazan** [KhronosGroup/OpenGL-Registry#198]
Here the enum group is TypeEnum.
```
    <command>
            <proto>void <name>v</name></proto>
            <param group="TypeEnum"><ptype>GLenum</ptype> <name>target</name></param>
            <param><ptype>GLuint</ptype> <name>index</name></param>
            <param len="COMPSIZE(target)"><ptype>GLint64</ptype> *<name>data</name></param>
        </command>
```
TypeEnum only contains values that are not valid arguments to `glGetInteger64i_v`.
```
        <group name="TypeEnum">
            <enum name="GL_QUERY_WAIT"/>
            <enum name="GL_QUERY_NO_WAIT"/>
            <enum name="GL_QUERY_BY_REGION_WAIT"/>
            <enum name="GL_QUERY_BY_REGION_NO_WAIT"/>
        </group>
```
I may be somehow misinterpreting the meaning of TypeEnum, as it is in some glGetFloat calls as well. I assumed that if group is an enum, it is one that describes the arguments.

**Comment by pdaniell-nv** [comment]
@oddhack is the XML expert and can probably explain this.

**Comment by oddhack** [comment]
See #266 (apparently Github doesn't auto-link issues & PRs based on the branch name, unlike gitlab).

**Comment by oddhack** [comment]
@joonazan please take a look at the PR - I can't assign you as a reviewer because Github.

**Comment by oddhack** [comment]
Closing - #266 should have addressed this.
