### ISSUE TITLE
ARB_framebuffer_sRGB doesn't specify fbconfig sorting

### ISSUE THREAD

**Issue by nwnk** [KhronosGroup/OpenGL-Registry#199]
It's worse than that, actually, it doesn't specify the interaction with fbconfigs _at all_. Presumably `GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB` is a property of both fbconfigs and visuals, but the implementation is given no guidance about how to handle, say, `glXChooseFBConfig`.

**Comment by oddhack** [comment]
I believe NVIDIA and Mesa are the only vendors who care about this (e.g. maintain their own GLX implementations). Hopefully they can identify common behavior WRT FBconfigs and document that. @pdaniell-nv, could you look at this for NVIDIA? @nwnk you may be as well posed as anyone to answer the question for Mesa?

**Comment by nwnk** [comment]
Mesa [now](https://gitlab.freedesktop.org/mesa/mesa/commit/faa29c0e2449e3d7521bc273d723012b537593df) treats `GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB` as exact match when specified, `GLX_DONT_CARE` otherwise. Prior to 2017 we didn't really have sRGB support, and the behavior in the interim hasn't been well defined.

**Comment by davidmaoamd** [comment]
AMD do have its own GLX implementation. It accept GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB/EXT as valid attribute but the attribute is irrelevant when sorting orders.

**Comment by pdaniell-nv** [comment]
@nwnk What's next for this issue?

**Comment by nwnk** [comment]
> @nwnk What's next for this issue?

I think this wants a spec update to ARB_framebuffer_sRGB. Right now it doesn't mention glXChooseFBConfig or glXGetFBConfigAttrib at all, nor specify that it's an exact match for selection but undefined for sorting (which seems to be the consensus here). I'll write that up.
