### ISSUE TITLE
glGetInternalformat - Incorrect documentation for parameter bufSize in the manpage

### ISSUE THREAD

**Issue by boumaour** [KhronosGroup/OpenGL-Registry#200]
Issue was already filed in the (defunct?) Khronos Bugzilla
https://www.khronos.org/bugzilla/show_bug.cgi?id=1454#c0
It looks like the manpage was fixed in the Parameters section, but not in the description.

Section 22.3 Internal Format Queries of the OpenGL 4.5 core spec says: 

> No more than `bufSize` integers will be written into `params`. If more data are
> available, they will be ignored and no error will be generated.

The man page for `glGetInternalFormat` has the following documentation for the parameter `bufSize`:

> Specifies the maximum number of integers of the specified width that may be written to `params` by the function.

This has been fixed in the manpage.

But later in the Description section:

> The information retrieved will be written to memory addressed by the pointer specified in `params`. No more than **`bufSize` basic machine units** will be written to this memory.

(3rd paragraph)

**Comment by oddhack** [comment]
Fixes in the OpenGL-Refpages repository.
