### ISSUE TITLE
Missing link pointing to Github for  issues in OpenGL ES

### ISSUE THREAD

**Issue by Khronoswebmaster** [KhronosGroup/OpenGL-Registry#201]
Around line 166 in opengl_es.php:

1 - There should be a link to the [Issue tracker](https://github.com/KhronosGroup/OpenGL-Registry/issues/) to make it somewhat easier for folks to post issues.
2 - Please change `github` to `GitHub`

    Please report problems as
        Issues in the <a href="index.php#repository">OpenGL-Registry</a> github
        repository.

**Comment by pdaniell-nv** [comment]
Sounds like a good idea to me. Assigned @oddhack.
