### ISSUE TITLE
glBlendFuncSeparate parameter table SRC1 typos

### ISSUE THREAD

**Issue by DJRBuckingham** [KhronosGroup/OpenGL-Registry#211]
Apologies if I've just misunderstood, but I believe the parameter table for glBlendFuncSeparate has typos for the SRC1 variants at the end.

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendFuncSeparate.xhtml

Specifically, GL_ONE_MINUS_SRC_COLOR and GL_ONE_MINUS_SRC_ALPHA both appear twice in the table. I believe these should be GL_ONE_MINUS_SRC**1**_COLOR and GL_ONE_MINUS_SRC**1**_ALPHA.

That said, I am far from an OpenGL expert and may well just be confused - apologies for wasting anyone's time if so. Also, I hope this is the correct place to report these sorts of issues.

**Comment by oddhack** [comment]
This is the right page for reference page issues - thanks! Fixed now.
