### ISSUE TITLE
Need to regenerate headers for Turing OpenGL extensions

### ISSUE THREAD

**Issue by nvpbrown** [KhronosGroup/OpenGL-Registry#216]
@oddhack,

When I submitted #214, I did not rebuild headers because my understanding is that the headers are rebuilt after various changes are merged to avoid possible conflicts in auto-generated files.  It appears that there was no rebuild done when the changes were merged to "master" and that the headers in the registry do not have the NVIDIA extensions.

Should I submit a pull request with regenerated headers, or do you want to build those?

Thanks,
Pat

cc += @dgkoch @pdaniell-nv @jeffbolznv

**Comment by oddhack** [comment]
Sorry! I did them on my local and neglected to push to github. Should be there now.

**Comment by pixeljetstream** [comment]
still don't see them

**Comment by dgkoch** [comment]
@pixeljetstream I see them. you need to look at the raw glext.h - the github viewer cuts off before the end of the file. 
https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/api/GL/glext.h

**Comment by nvpbrown** [comment]
I just fetched the latest "master" and confirmed the fix.  Thanks for your help.

**Comment by pixeljetstream** [comment]
glcorearb.h is not updated

**Comment by nvpbrown** [comment]
This is my fault -- I included:

`supported="gl"`

for these entries, but to get into glcorearb.h, it appears you need

`supported="gl|glcore"`

I can prepare an MR for this.

**Comment by nvpbrown** [comment]
I created pull request #218 to address @pixeljetstream's glcorearb.h issue.  I generated headers locally but did not include them in the pull request.
