### ISSUE TITLE
NV vertex/uniform buffer unified memory and glcorearb.h

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/OpenGL-Registry#217]
Both extensions require glEnable/DisableClientState
these being deprecated are however missing in glcorearb.h

**Comment by oddhack** [comment]
I guess a vendor extension can unilaterally pull a deprecated command back into the core profile, technically speaking, but it seems a bit out of scope and maybe a call the WG ought to make, not me. @pdaniell-nv, can you put this on the agenda?

**Comment by pdaniell-nv** [comment]
@pixeljetstream would it be reasonable that these extensions to only be defined for compatibility profile?

**Comment by jeffbolznv** [comment]
IMO, no, these extensions have been shipping this way for nearly 10 years, it makes no sense to defeature them now.

**Comment by pdaniell-nv** [comment]
It's unfortunate that not all functions are available in glcorearb.h to an extension that brings them back from the compatibility profile. However, we've decided not to put glEnableClientState/glDisableClientState back in glcorearb.h. Instead glext.h can be used to get access to these compatibility functions.
