### ISSUE TITLE
Difficulty pushing new extension to OpenGL-Registry 

### ISSUE THREAD

**Issue by jackohound** [KhronosGroup/OpenGL-Registry#22]
I’m trying to push a new OpenGL ES extension to https://github.com/KhronosGroup/OpenGL-Registry,

I created a local branch “add_QCOM_framebuffer_foveated” , tracking origin/master.   I’ve followed the wiki.  When I attempt to push to the remote repo, I get this error:

```
$ git remote -v
origin  https://github.com/KhronosGroup/OpenGL-Registry.git (fetch)
origin  https://github.com/KhronosGroup/OpenGL-Registry.git (push)
$ git push origin add_QCOM_framebuffer_foveated
remote: Permission to KhronosGroup/OpenGL-Registry.git denied to jackohound.
fatal: unable to access 'https://github.com/KhronosGroup/OpenGL-Registry.git/': The requested URL returned error: 403
```
The machine I am pushing from is running Ubuntu Linux 14.04.  
**I’ve confirmed that I can push to other Github repos from the same computer without problem**.  

Anyone seen this before, or have ideas why I cannot push to OpenGL-Registry?

**Comment by oddhack** [comment]
You have to propose a pull request from your personal account - only a couple of gatekeepers are members of KhronosGroup and the appropriate Team, and can push branches directly.

**Comment by oddhack** [comment]
Ignore bogus extra autoclose above.
