### ISSUE TITLE
gl2platform.h and gl3platform.h have different license than everything else

### ISSUE THREAD

**Issue by tweenk** [KhronosGroup/OpenGL-Registry#228]
The GLES header files gl2platform.h and gl3platform.h have the Apache license, while all other headers have the MIT license. Since these files are largely trivial, could they be relicensed to the same license as the rest of the official Khronos headers?

**Comment by oddhack** [comment]
What's your use case? Is this a GPL2/LGPL2 issue?

**Comment by oddhack** [comment]
Closing this for lack of feedback. If we do license changes, it would almost certainly be to place code-like files that aren't already under Apache 2, under it, since that's the evolving Khronos copyright standard.
