### ISSUE TITLE
Document extension types and spec update policies in the registry index

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-Registry#235]
This is to track a request from @pdaniell-nv that we document the different types of extensions (vendor, EXT, KHR/ARB/OES, etc.) as well as the policies for updating non-current GL/ES extension specs (which, generally, we don't do unless there's a critical functionality issue affecting something like ANGLE, which is very widely used and based on an older ES API version). If there are particular aspects of these issues outside developers need clarified, they are welcome to identify them here as well.

**Comment by pdaniell-nv** [comment]
This issue is being tracked internally here: https://gitlab.khronos.org/opengl/API/issues/103

**Comment by oddhack** [comment]
Proposed update here: https://github.com/KhronosGroup/OpenGL-Registry/pull/255 - needs signoff by @pdaniell-nv .

**Comment by oddhack** [comment]
#255 was accepted, so closing this. #265 is pending for minor wording tweaks in the boilerplate comments about update policy.
