### ISSUE TITLE
EnableCap's Group specification seems old

### ISSUE THREAD

**Issue by tkaaad97** [KhronosGroup/OpenGL-Registry#238]
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnable.xhtml

From the glEnable documentation, some constants do not exist in the EnableCap's group.

Below constants are missing.

```
GL_CLIP_DISTANCE
GL_DEBUG_OUTPUT
GL_DEBUG_OUTPUT_SYNCHRONOUS
GL_DEPTH_CLAMP
GL_FRAMEBUFFER_SRGB
GL_MULTISAMPLE
GL_PRIMITIVE_RESTART
GL_PRIMITIVE_RESTART_FIXED_INDEX
GL_PROGRAM_POINT_SIZE
GL_RASTERIZER_DISCARD
GL_SAMPLE_ALPHA_TO_COVERAGE
GL_SAMPLE_ALPHA_TO_ONE
GL_SAMPLE_COVERAGE
GL_SAMPLE_MASK
GL_SAMPLE_SHADING
GL_TEXTURE_CUBE_MAP_SEAMLESS
```

Should EnableCap's specification be modified based on gl4 documentation ?

**Comment by oddhack** [comment]
Sounds reasonable. Can you submit a PR to do this?

**Comment by tkaaad97** [comment]
I made a PR #239.

**Comment by tkaaad97** [comment]
thanks for merging.
