### ISSUE TITLE
At least one function have inconsistent argument names

### ISSUE THREAD

**Issue by Deamon87** [KhronosGroup/OpenGL-Registry#257]
Here https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawElementsInstancedBaseVertexBaseInstance.xhtml
the argument after `GLvoid *indices` is named `GLsizei primcount` and referenced under this name in function description.

But in header file https://www.khronos.org/registry/OpenGL/api/GL/glcorearb.h same function has this definition:
`GLAPI void APIENTRY glDrawElementsInstancedBaseVertexBaseInstance (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex, GLuint baseinstance);`
Same argument is named `instancecount`.

**Comment by pdaniell-nv** [comment]
In the OpenGL 4.3 spec we modified all uses of "primcount" to be "instancecount", so the refpage should be updated to call this parameter "instancecount".

**Comment by oddhack** [comment]
@Deamon87 this is open on the wrong repository - can you move it to OpenGL-Refpages? Thanks.

@pdaniell-nv note this affects all the core draw call pages with this parameter, not just this one.

**Comment by oddhack** [comment]
@pdaniell-nv @Deamon87 please review https://github.com/KhronosGroup/OpenGL-Refpages/pull/65 .
