### ISSUE TITLE
GL_CLIP_DISTANCE in gl.xml

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#267]
`<group name="EnableCap">` has `<enum name="GL_CLIP_DISTANCE"/>`
- There is no API nor extension which would allow glEnable(GL_CLIP_DISTANCE).
- GL_CLIP_DISTANCE has no value defined in gl.xml.

**Comment by oddhack** [comment]
Presumably that should have been GL_CLIP_DISTANCE0..7. Want to propose an MR?
N.b. the last time the groups were actively maintained was about 1999. They got bulk-imported when the SGI .spec -> XML conversion was done and there have been some public MRs, but basically they're hopelessly out of date.

**Comment by pdaniell-nv** [comment]
@tsuoranta Are you able to propose a PR to fix this? Thank.

**Comment by tksuoran** [comment]
Fix for this issue is included in https://github.com/KhronosGroup/OpenGL-Registry/pull/274 which has some other fixes to enums as well.

**Comment by pdaniell-nv** [comment]
Since https://github.com/KhronosGroup/OpenGL-Registry/pull/274 is merged closing this issue.
