### ISSUE TITLE
Add meta tag for viewing on mobile devices

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-Registry#28]
Some time ago in email, @Khronoswebmaster suggested that we should:

>add the following just below the <title></title> tags: 
>
>    \<meta name="viewport" content="width=device-width”/>
>
> With it, the pages flow properly and the text is readable.

Should revisit this now.

**Comment by pdaniell-nv** [comment]
Sounds good. Assigned to @oddhack.

**Comment by oddhack** [comment]
TBH I'm not sure at this point which files were being referred to. The .php files suck in a framework that may already do this but is in any event outside our control. There's some very old static HTML that maybe could use it - when I tried viewing in Chrome on my smartphone it popped up a "Make Mobile Friendly?" dialog that did... something, when pressed, that affected how the page looked. But I don't know what. Given that all (5) of the .html files are well over a decade old and already marked obsolete, I propose we just close this and wait for a specific problem report.

**Comment by Khronoswebmaster** [comment]
I believe this was meant for SPIR mobile pages fed from SVN:
https://cvs.khronos.org/svn/repos/SPIRV/trunk/Version1.0Rev2/SPIRV.mobile.html

The issue still exists on those pages and perhaps other specs.

**Comment by oddhack** [comment]
@Khronoswebmaster OK. The SPIR-V registry is managed entirely by that WG now, so maybe ping their repository with an issue instead. Closing this.
