### ISSUE TITLE
Link returns 404 on the "Tutorials and How To Guides" section.

### ISSUE THREAD

**Issue by tommai78101** [KhronosGroup/OpenGL-Registry#286]
Link to the section:

https://www.khronos.org/opengl/wiki/Getting_Started#Tutorials_and_How_To_Guides

The first link, named, "Develop with OpenGL 3.1 from scratch (Français)" now returns 404 when opened. This content no longer exists.

http://www.siteduzero.com/tutoriel-3-421558-developpez-vos-jeux-video-3d-avec-opengl-3-1.html

**Comment by tommai78101** [comment]
And then the second link goes to BitBucket's homepage.

The link should be updated to this one, I think?

https://bitbucket.org/alfonse/gltut/wiki/Home

**Comment by Perksey** [comment]
This issue is in the incorrect repository.

**Comment by tommai78101** [comment]
Whoops, I did not realize this. Is this the correct repository?

https://github.com/KhronosGroup/Khronosdotorg

**Comment by Perksey** [comment]
Yep :) Feel free to close this issue once you've copied and pasted it in there!

**Comment by oddhack** [comment]
I fixed it, although it says "in moderation" and I have no idea who the moderator is. If it's the Khronos webmaster, he's on vacation for a bit and may not get to this until mid-July.
