### ISSUE TITLE
VULKANPROCNV undefined 

### ISSUE THREAD

**Issue by krogueintel** [KhronosGroup/OpenGL-Registry#29]
The type VULKANPROCNV is not defined, but used (for the extension GL_NV_draw_vulkan_image) in a typedef. Naturally, this makes projects fail to compile that include GL/glcorearb.h GL/glext.h or GLES2/gl2ext.h

I was not sure if this bug belonged in Bugzilla or here, for reference the bug in Bugzilla is located at https://www.khronos.org/bugzilla/show_bug.cgi?id=1943

**Comment by pdaniell-nv** [comment]
Thank for reporting this issue. I'll take a look today and post a fix.

**Comment by oddhack** [comment]
It belongs here. Please close the bugzilla.
