### ISSUE TITLE
MESA_shader_integer_functions needs to have ES dependencies section added

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-Registry#3]
When this was registered, I was told that "the spec is applicable to both desktop OpenGL and OpenGL ES". However, the dependencies section does not say what the required version of ES or ESSL is. Until someone from Mesa corrects this, it will not be tagged as part of the ES registry in extensions/registry.py, just the GL registry.

https://www.khronos.org/registry/OpenGL/extensions/MESA/MESA_shader_integer_functions.txt

**Comment by TobiasHector** [comment]
Assigning to myself until I can figure out if the spec author has a github account.

**Comment by kaydenl** [comment]
It looks like Mesa exposes this extension with ES 3.0 / GLSL ES 3.00.

Do we just need:
-    GLSL 1.30 is required.
+    GLSL 1.30 (OpenGL) or GLSL ES 3.00 (OpenGL ES) is required.
or do we need additional language?

I'm happy to update the spec in the Mesa repository.

**Comment by oddhack** [comment]
@kaydenl please review #42, ignore #41. Thanks.
