### ISSUE TITLE
Possible error in ARB_texture_compression_bptc document

### ISSUE THREAD

**Issue by achurch** [KhronosGroup/OpenGL-Registry#310]
According to the ARB_texture_compression_bptc extension document, in modes with shared P-bits, there is one P-bit per endpoint (https://github.com/KhronosGroup/OpenGL-Registry/blob/master/extensions/ARB/ARB_texture_compression_bptc.txt#L372-L374):
```
[...] If the format has a
shared P-bit, there are two bits for endpoints 0 and 1 from low to
high. [...]
```
However, in Microsoft's documentation of the DirectX BC7 compression method, which I understand to be the same as BPTC (please correct me if not), there is instead one P-bit per subset (https://docs.microsoft.com/en-us/windows/win32/direct3d11/bc7-format-mode-reference):
```
RGBP 6.6.6.1 endpoints with a shared P-bit per subset)
```
Microsoft's reference BC7 decoder also treats shared P-bits as per subset, not per endpoint (https://github.com/microsoft/DirectXTex/blob/master/DirectXTex/BC6HBC7.cpp#L3293-L3301):
```
// shared pbits
for (uint8_t ch = 0; ch < BC7_NUM_CHANNELS; ch++)
{
    for (size_t i = 0; i <= uPartitions; i++)
    {
        pFixedEndpoints[i].A[ch] = static_cast<uint8_t>((pFixedEndpoints[i].A[ch] << 1) | pbits[i]);
        pFixedEndpoints[i].B[ch] = static_cast<uint8_t>((pFixedEndpoints[i].B[ch] << 1) | pbits[i]);
    }
}
```
Coincidentally, the only mode which uses shared P-bits (mode 1) has 2 subsets, so this difference in interpretations does not change the number of P-bits and thus does not affect the decoding of the rest of the block, though it does result in differing low-order bits of the resulting color values.

Is this an intentional difference between OpenGL BPTC and DirectX BC7, or is the BPTC extension document incorrectly worded?

**Comment by pdaniell-nv** [comment]
@fluppeteer Do you have any thoughts on this?

**Comment by pdaniell-nv** [comment]
Fix for the OpenGL ES EXT_texture_compression_bptc extension spec is here: https://github.com/KhronosGroup/OpenGL-Registry/pull/337
