### ISSUE TITLE
[gl.xml] framebuffer attachments has incorrect and missing values

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#313]
`GL_MAX_COLOR_ATTACHMENTS`, `GL_MAX_COLOR_ATTACHMENTS_EXT` and `GL_MAX_COLOR_ATTACHMENTS_NV` do not belong to `FramebufferAttachment` enum group.

`GL_STENCIL_ATTACHMENT`, `GL_STENCIL_ATTACHMENT_EXT` and `GL_STENCIL_ATTACHMENT_OES` are missing from `FramebufferAttachment` enum group.

Fix proposal in #312 

Related question: Split to separate issue #317

**Comment by Perksey** [comment]
Safe to be closed.
