### ISSUE TITLE
[gl.xml] Invalidate*Framebuffer() attachments accept GL_COLOR, GL_DEPTH, GL_STENCIL

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#317]
`glInvalidate*Framebuffer()` and `glDiscardFramebuffer()` accept `GL_COLOR`, `GL_DEPTH` and `GL_STENCIL` as attachments. In current gl.xml these gl commands use `FramebufferAttachment` as enum group for attachment, and color/depth/stencil is not included in that enum group.

I propose that we create a new enum group `InvalidateFramebufferAttachment`, which would contain same enums as `FramebufferAttachment` enum group, and also contains `GL_COLOR`, `GL_DEPTH` and `GL_STENCIL`.

Fix proposal in #316.

**Comment by Perksey** [comment]
Safe to be closed.
