### ISSUE TITLE
EXT_disjoint_timer_query: gl.xml missing glGetInteger64vEXT

### ISSUE THREAD

**Issue by ascent12** [KhronosGroup/OpenGL-Registry#326]
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt mentions in the "Dependencies" section that

>Interaction: This extension adds GetInteger64vEXT if OpenGL ES 3.0 is not supported

However, there is no specification of this function anywhere in gl.xml or in the final gl2ext.h header.
Without this, an application targeting GLES2 that wants to use this extension cannot query GL_TIMESTAMP_EXT to its full precision if GL_QUERY_COUNTER_BITS_EXT is greater than 32, e.g. Mesa on Linux.

**Comment by oddhack** [comment]
It would not be hard to inject this into gl.xml, but it's worth asking first if this is a real-world use case -  *is* there a GLES2 implementation supporting this extension that isn't also a GLES3 implementation at the same time? If so you're welcome to construct a PR against gl.xml to alias the core function and add a gles2-specific requirement for it in the extension interface block.

**Comment by tpalli** [comment]
I've created a PR here:
https://github.com/KhronosGroup/OpenGL-Registry/pull/329

**Comment by tpalli** [comment]
@oddhack what comes to the GLES2 driver question, I know that we have drivers in Mesa that support only GLES2 (+ possibly subset of GLES3.x features), this could be useful for such a driver.

**Comment by oddhack** [comment]
I overlooked that the extension specification itself will also need some text added to define the GetInteger64vEXT command, since that's present nowhere else in the API. That could probably most easily be cloned from the GL_APPLE_sync spec since they did a similar thing, although I haven't verified that's identical to the language for GetInteger64v in the ES 3.2 spec.

**Comment by oddhack** [comment]
Added #338 with the spec language for GetInteger64vEXT.
