### ISSUE TITLE
Invalid enums referenced by various groups.

### ISSUE THREAD

**Issue by Perksey** [KhronosGroup/OpenGL-Registry#327]
I would PR this straight in, but I need to confirm whether these are incorrect references or missing references.

cc:
NV @pdaniell-nv 
ARB @oddhack 
Silk.NET @frederikja163 

```
GL_RGB_NV
GL_ALPHA_NV
GL_FLOAT_NV
GL_DOUBLE_NV
GL_PROGRAM_STRING
GL_UNSIGNED_BYTE_SUN
and more...
```

Writing this, it seems that it's been assumed that all enums within groups with vendor suffixes too have suffixes. What's the best way to resolve this? Remove the suffixes from the enum group names, or just fix the references within the groups?

**Comment by pdaniell-nv** [comment]
There's probably some historical reason those suffixed tokens are still there. I think the simplest thing would be to just remove the suffixes so the groups reference valid tokens.
