### ISSUE TITLE
gl.xml: Several texture format enums are missing from enum groups

### ISSUE THREAD

**Issue by null77** [KhronosGroup/OpenGL-Registry#339]
We noticed this when writing a "glenum to string" method. Several extension format enums and other odd enums are missing from the enum group sections.

We'll propose a patch that fixes the omissions that we ran into.

**Comment by frederikja163** [comment]
I think a list of the enums that are missing from the enum groups would be apriciated, although it might not be necessary with #335

**Comment by pdaniell-nv** [comment]
Is this still an issue given all the XML changes from https://github.com/KhronosGroup/OpenGL-Registry/issues/335?

**Comment by null77** [comment]
Probably not. It's on us to switch to the new method so closing this out.
