### ISSUE TITLE
`LICENSE` file(s)

### ISSUE THREAD

**Issue by usagi** [KhronosGroup/OpenGL-Registry#340]
I think, the repos need add the `LICENSE` file(s). In now, license informations exists in an each header files. But it is not a kind for users.

**Comment by oddhack** [comment]
It's difficult to capture the mix of licenses in the repository. Some are Apache 2; some are BSD; some of the API specs are under the current Khronos spec license which allows republication but not modification; some of the older specs are under older Khronos and SGI licenses with different and more restrictive terms; many of the extension specs are implicitly copyright by the company that created them and asked Khronos to put them in the registry, but don't actually have an explicit copyright; some are little tiny text files we never bothered to copyright, etc. - I don't know what a LICENSE file could contain other than acknowledging that people need to go by the copyrights on the individual files or use their best judgement if there isn't one. If you have a specific usage question we could try to answer it.

**Comment by usagi** [comment]
Ah, I didn't understood the situation but in now, I understood it. I checked only a small part of the APIs. I made this issue because inconvinient when I need a clear license check for a software under development. I am sorry for my lack of consideration toward the repos. Thank you @oddhack, for the good explanations.
