### ISSUE TITLE
GL_EXT_YUV_target. How to read/write  data from the YUV texture?

### ISSUE THREAD

**Issue by BoysFight** [KhronosGroup/OpenGL-Registry#347]
Hi, there. 
I am trying to use the GL_EXT_YUV_target to process yuv data on android. https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_YUV_target.txt, the link describes something about the glsl, but i can not find how to read/write the data from the texture. 
Are there samples  that using this feature?

**Comment by pdaniell-nv** [comment]
A better place to get this answered is probably here: https://community.khronos.org/
