### ISSUE TITLE
Texture array support for RGTC

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/OpenGL-Registry#349]
From the way the extension specs (`ARB_texture_compression_rgtc` and `EXT_texture_compression_rgtc`) are written, it seems that `CompressedTexImage3D` should always fail with `INVALID_ENUM` when used with RGTC formats.

This is justified in the spec by comparing 3D slices with 3D blocks:
> Should these formats be allowed to specify 3D texture images when `NV_texture_compression_vtc` is supported?
>
> RESOLVED: The `NV_texture_compression_vtc` stacks 4x4 blocks into 4x4x4 bricks.  It may be more desirable to represent compressed 3D textures as simply slices of 4x4 blocks. 
> However the `NV_texture_compression_vtc` extension expects data passed to the `glCompressedTexImage` commands to be "bricked" rather than blocked slices.

However, it's not clear why this should prevent RGTC from being used with 2D arrays.

**Comment by pdaniell-nv** [comment]
There is no restriction from using RGTC with glCompressedTexImage3D and a target of GL_TEXTURE_2D_ARRAY. The RGTC extension was folded into OpenGL 3.0 core, and that spec and the latest OpenGL 4.6 spec allow RGTC to be used in 2D arrays.

From the OpenGL 4.6 spec:
> An INVALID_OPERATION error is generated by CompressedTexImage3D if internalformat is one of the EAC, ETC2, or RGTC formats and either
> border is non-zero, or target is not TEXTURE_2D_ARRAY, TEXTURE_CUBE_-
> MAP or TEXTURE_CUBE_MAP_ARRAY.

As a general rule of thumb, the OpenGL core specs should be referenced instead of the extension specs after an extension has been integrated to the core spec. From the [ARB spec](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_texture_compression_rgtc.txt):
```
Specification Update Policy

    Khronos-approved extension specifications are updated in response to
    issues and bugs prioritized by the Khronos OpenGL Working Group. For
    extensions which have been promoted to a core Specification, fixes will
    first appear in the latest version of that core Specification, and will
    eventually be backported to the extension document. This policy is
    described in more detail at
        https://www.khronos.org/registry/OpenGL/docs/update_policy.php
```

**Comment by lexaknyazev** [comment]
@pdaniell-nv 
This certainly clarifies OpenGL support, thanks.

On the other hand, `EXT_texture_compression_rgtc` is defined also for OpenGL ES and was never merged into the GL ES spec. So technically, RGTC 2D arrays are still unsupported there.

**Comment by pdaniell-nv** [comment]
The way the EXT_texture_compression_rgtc extension spec was updated to support OpenGL ES 3.2 should allow RGTC textures to be used as 2D arrays for OpenGL ES. All it did was add the RGTC formats to table 8.17. The existing language for glCompressTexImage3D allows any of those compressed texture formats to be used with 2D array targets.

You can ignore the unclear wording in issue 13 regarding 3D textures. The important part is the normative language in the OpenGL ES 3.2 core spec.
