### ISSUE TITLE
Enumeration enum start attribute not updated inside Oculus enumeration of OpenGL xml registry

### ISSUE THREAD

**Issue by alberto-cerato** [KhronosGroup/OpenGL-Registry#35]
Hello,
it look there is a trivial bug in the the start attribute of the Oculus enumeration inside the OpenGL xml registry
https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml

...
 <enum value="0x9633" name="GL_FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR"/>
       <unused start="0x9633" end="0x963F" vendor="Oculus"/>
...

Added an issues here since it does not look a Khronos specification problem to me.

**Comment by oddhack** [comment]
Fixed, thanks. The unused tag could be autogenerated - it's really just for humans who are allocating new enums - but have never gotten around to it.
