### ISSUE TITLE
DepthRangeArraydvNV and DepthRangeIndexeddNV not defined in XML

### ISSUE THREAD

**Issue by ReinUsesLisp** [KhronosGroup/OpenGL-Registry#350]
The interaction with `NV_depth_buffer_float` of `ARB_viewport_array` is not defined in [gl.xml](https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml). The functions added by this interaction are `DepthRangeArraydvNV` and `DepthRangeIndexeddNV`.

The extension [specification](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_viewport_array.txt) defines these functions below `Interactions with NV_depth_buffer_float`.

Edit: Issue redirected from glad [here](https://github.com/Dav1dde/glad/issues/242).

**Comment by Perksey** [comment]
I'm willing to PR this unless these functions were intentionally left out?

**Comment by Dav1dde** [comment]
Probably not that easy since if I read the spec correctly these functions should only exist if the other extension is enable too. Maybe not worth to be correct and just to always add the functions.

**Comment by oddhack** [comment]
I'd stick them inside something like this:

```
<require comment="Supported only if (name of other extension) is also supported">
    <command name="glWhatever"/>
    ...
</require>
```

The schema could be extended to explicitly address this scenario if it's important to capture mechanically, but we haven't done that yet.

**Comment by Dav1dde** [comment]
Thinking about it, this should be good enough since it is a runtime requirement anyways. Can't ever know at compile time if these functions should exist or not.

**Comment by pdaniell-nv** [comment]
This was probably an oversight. It would be great if someone contributed a PR to fix this.

**Comment by Perksey** [comment]
On it.
