### ISSUE TITLE
[gl.xml] non-parsable groups "DataType" and "FfdMaskSGIX"

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#351]
1. Line 1017:
	```
			<group name="DataType" comment="See enums block below"/>
	```
	There isn't anything in enums tag, refering to this, but on line 240:
	```
			<group name="DataTypeEXT">
				<enum name="GL_SCALAR_EXT"/>
				<enum name="GL_VECTOR_EXT"/>
				<enum name="GL_MATRIX_EXT"/>
			</group>
	```
	
2. Line 1264:
	```
			<group name="FfdMaskSGIX" comment="See enums section below. Was SGIXFfdMask"/>
	```
	This time there are enums refering to this, on line 5137:
	```
		<enums namespace="GL" group="FfdMaskSGIX" type="bitmask">
			<enum value="0x00000001" name="GL_TEXTURE_DEFORMATION_BIT_SGIX"/>
			<enum value="0x00000002" name="GL_GEOMETRY_DEFORMATION_BIT_SGIX"/>
		</enums>
	```
	
Still, in both cases comments are used, which aren't parsable.

I guess `DataType` group should be removed, as it isn't used anywhere (instead all commands use `DataTypeEXT`).
And `FfdMaskSGIX` should be properly filled.

**Comment by Perksey** [comment]
The group blocks are deprecated in favour of group attributes as described in #335 and #343. Please check if your issue is still present with the new schema. If the PR fixes your issue, please close it.

**Comment by SunSerega** [comment]
I seen issue, but not pull before posting...
I'll close this when/if pull get's merged.
