### ISSUE TITLE
[glx.xml] missing <ptype> for parameter of glXSet3DfxModeMESA

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#354]
<command>
        <proto><ptype>GLboolean</ptype> <name>glXSet3DfxModeMESA</name></proto>
        <param>GLint <name>mode</name></param>
    </command>
`GLint` should be wrapped in `<ptype>` tag.

**Comment by oddhack** [comment]
Closed by 2223f5bebde4aa6b170fb32cdaaf580703fddb67 (which was mis-labelled as closing issue 22).
