### ISSUE TITLE
[xml] MaterialFace group used but not defined

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#355]
```
        <command>
            <proto><ptype>GLuint</ptype> <name>glBindMaterialParameterEXT</name></proto>
            <param group="MaterialFace"><ptype>GLenum</ptype> <name>face</name></param>
            <param group="MaterialParameter"><ptype>GLenum</ptype> <name>value</name></param>
        </command>
```
(this is only one of functions using `MaterialFace`)

There is an actual group (which is deprecated) `MaterialFace`:
```
        <group name="MaterialFace" comment="Deprecated, use the group attributes instead.">
            <enum name="GL_BACK"/>
            <enum name="GL_FRONT"/>
            <enum name="GL_FRONT_AND_BACK"/>
        </group>
```
And there is `ColorMaterialFace` group (which is properly defined):
```
        <enum value="0x0404" name="GL_FRONT" group="ColorBuffer,ColorMaterialFace,CullFaceMode,DrawBufferMode,ReadBufferMode,StencilFaceDirection"/>
        <enum value="0x0405" name="GL_BACK" group="ColorBuffer,ColorMaterialFace,CullFaceMode,DrawBufferMode,ReadBufferMode,StencilFaceDirection"/>
        <enum value="0x0408" name="GL_FRONT_AND_BACK" group="ColorBuffer,ColorMaterialFace,CullFaceMode,DrawBufferMode,StencilFaceDirection"/>
```

**Comment by Perksey** [comment]
Thanks for reporting this! We always welcome PRs to help improve and maintain the correctness of the new-syntax groupings. If not done by a community member, this will be included next time we have a group sprint here at Ultz.

**Comment by oddhack** [comment]
I'm just going to assign this and similar to @Perksey since you're stepping up to volunteer - thanks.

**Comment by Perksey** [comment]
Ah no problem, I do my best to try and help out with the GL spec as I'm a prominent stakeholder for it, so I have no problem tackling issues such as these.
