### ISSUE TITLE
[xml] ColorTableParameterPNameSGI group used but not defined

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#356]
```
        <command>
            <proto>void <name>glColorTableParameterfv</name></proto>
            <param group="ColorTableTarget"><ptype>GLenum</ptype> <name>target</name></param>
            <param group="ColorTableParameterPNameSGI"><ptype>GLenum</ptype> <name>pname</name></param>
            <param group="CheckedFloat32" len="COMPSIZE(pname)">const <ptype>GLfloat</ptype> *<name>params</name></param>
            <glx type="render" opcode="2054"/>
        </command>
```
(this is only one of functions using `ColorTableParameterPNameSGI`)

I think these are the enums that should be passed as `ColorTableParameterPNameSGI`:
```
    COLOR_TABLE_SCALE_SGI                0x80D6
     COLOR_TABLE_BIAS_SGI                0x80D7
```
But this info should be further checked before applying it.

**Comment by Perksey** [comment]
Thanks for reporting this! We always welcome PRs to help improve and maintain the correctness of the new-syntax groupings. If not done by a community member, this will be included next time we have a group sprint here at Ultz.
