### ISSUE TITLE
[xml] IglooFunctionSelectSGIX group used but not properly defined

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#357]
```
        <command>
            <proto>void <name>glIglooInterfaceSGIX</name></proto>
            <param group="IglooFunctionSelectSGIX"><ptype>GLenum</ptype> <name>pname</name></param>
            <param group="IglooParameterSGIX" len="COMPSIZE(pname)">const void *<name>params</name></param>
            <glx type="render" opcode="200"/>
        </command>
```
There is only commented out group defined with depricated syntax:
```
        <group name="IglooFunctionSelectSGIX" comment="Private (internal) extension SGIX_igloo_interface">
            <!--<enum name="GL_IGLOO_FULLSCREEN_SGIX"/>-->
            <!--<enum name="GL_IGLOO_VIEWPORT_OFFSET_SGIX"/>-->
            <!--<enum name="GL_IGLOO_SWAPTMESH_SGIX"/>-->
            <!--<enum name="GL_IGLOO_COLORNORMAL_SGIX"/>-->
            <!--<enum name="GL_IGLOO_IRISGL_MODE_SGIX"/>-->
            <!--<enum name="GL_IGLOO_LMC_COLOR_SGIX"/>-->
            <!--<enum name="GL_IGLOO_TMESHMODE_SGIX"/>-->
        </group>
```
I understand that `SGIX_igloo_interface` is not just internal, but also deprecated extension.
But `IglooFunctionSelectSGIX` group is used by function xml, so it still need's to be properly defined in same xml.

**Comment by Perksey** [comment]
I think the best solution here is to comment out all remnants of that extension entirely, or remove the group attributes from the parameters.

**Comment by SunSerega** [comment]
I would prefer to have all remains commented out, over leaving `<ptype>GLenum</ptype>` parameter without group attribute.

But i don't think it would hurt to still support this extension.

**Comment by oddhack** [comment]
This is an ancient SGI extension kept around for historical completeness. It was actually not intended for use by anything but Igloo, SGI's Iris GL -> OpenGL translation layer, and exceedingly unlikely to be supported by anything built in the last decade. There is no harm in un-commenting the enums for this private extension although very little utility either - it's really just there in case for some reason in the future, someone wants to know what that extension or enum was about.

**Comment by SunSerega** [comment]
> although very little utility either

Well, as i said - i already read that it's internal and deprecated before posting. But still posted for completeness sake. The fact that group can be used, but not defined is not documented in .pdf, and sounds too wrong to be documented.

But it should be okay to mark the extension being dead as you said in #358, and then leave `<ptype>GLenum</ptype>` without group attribute. Because dead extensions, as you said, should be ignored by code using .xml's.

**Comment by Perksey** [comment]
> But it should be okay to mark the extension being dead as you said in #358, and then leave <ptype>GLenum</ptype> without group attribute. Because dead extensions, as you said, should be ignored by code using .xml's.

I think this is probably the best solution

**Comment by pdaniell-nv** [comment]
@Perksey I notice there are a bunch of issues you've added to your todo list. Shall I assign those issues to you?

**Comment by Perksey** [comment]
Yeah that's probably best, thanks.
