### ISSUE TITLE
[xml] TexBumpParameterATI group used but not defined

### ISSUE THREAD

**Issue by SunSerega** [KhronosGroup/OpenGL-Registry#358]
```
        <command>
            <proto>void <name>glTexBumpParameterfvATI</name></proto>
            <param group="TexBumpParameterATI"><ptype>GLenum</ptype> <name>pname</name></param>
            <param len="COMPSIZE(pname)">const <ptype>GLfloat</ptype> *<name>param</name></param>
        </command>
```
(this is only one of functions using `TexBumpParameterATI`)

`TexBumpParameterATI` is only defined in deprecated syntax:
```
        <group name="TexBumpParameterATI" comment="Deprecated, use the group attributes instead.">
            <enum name="GL_BUMP_ROT_MATRIX_ATI"/>
        </group>
```

**Comment by Perksey** [comment]
Thanks for reporting this! We always welcome PRs to help improve and maintain the correctness of the new-syntax groupings. If not done by a community member, this will be included next time we have a group sprint here at Ultz.

**Comment by SunSerega** [comment]
You didn't really need to send this 4 time (although i'm kinda concerned if it would be better to have a single issue describing all 4 groups). I have github mail notifications on, besides generally liking to check myself for things i participated it.

About PR's - it's a bit more work for me (though, i would done it if this is only intended way of reporting about this). And it looks to me like using shotgun to kill a chicken. It would be inaccurate ('m not even sure if all 4 request are same lvl valid) and generally a waste (of time in this case, from both mine, and from person reviewing it. At least if they gonna properly check, which is what i would hope for).

---

Also, can you tell more about Ultz and "group sprint" (preferably with links)? If you don't wanna go offtopic here - you can send it to `sunserega2@gmail.com`.

**Comment by Perksey** [comment]
Ultz is the company backing Silk.NET - a bindings library to OpenGL(ES) for .NET Standard. Occasionally @frederikja163 or myself (but normally Fred) will implement a spree of group fixes and PR them back in, hence the name "group sprint".

**Comment by Perksey** [comment]
I personally strive to review in-detail each PR affecting the groupings.

**Comment by oddhack** [comment]
My vague recollection is that ATI (now AMD) stopped supporting that extension many years ago. I think it was a very early fixed-function lighting and shading interface that stopped making sense as soon as people started writing OpenGL 2.0 era shader programs. Again it can be supported but is of little relevant.

Structurally the right way to deal with this stuff would be to identify extensions that are absolutely dead and of no interest, and tag them that way in the \<extension> tags (e.g. supported="deprecated" or really anything other than "gl*"). Then they would not (or at least, should not be) selected by code processing the XML, but the interface definitions would be retained for posterity.

The problem with this is that it's really hard to be sure when an extension is completely dead.

**Comment by SunSerega** [comment]
> Structurally the right way to deal with this stuff would be to identify extensions that are absolutely dead and of no interest

Yes, sounds right to me. Expect "deprecated" sounds like a thing that *would* be removed, not something already fully unsupported, so it's better to use something else.

**Comment by Perksey** [comment]
> Structurally the right way to deal with this stuff would be to identify extensions that are absolutely dead and of no interest, and tag them that way in the <extension> tags (e.g. supported="deprecated" or really anything other than "gl*")

> Yes, sounds right to me. Expect "deprecated" sounds like a thing that would be removed, not something already fully unsupported, so it's better to use some other string.

There is already a `disabled` api but I don't think "dead" extensions are a place for them, and they do deserve their own group like `deprecated` api. Then again, they both serve the same purpose but I still think unsupported extensions should be set aside from extensions that shouldn't be used (like the experimental NVIDIA extensions currently residing in the disabled group)
