### ISSUE TITLE
Extensions registry could be externally (more) usable externally.

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#367]
Extensions registry (`extensions/registry.py`) would be significantly more usable externally if it was data driven, for example, JSON formatted.

Fix proposal in #366 (done with a bunch of regex search and replaces).

My use case for extensions registry is that I want to be able to enumerate all extensions in C/C++, for the purpose of modifying glslang so that preprocessing and compilation could be performed with user specified extensions made available or unavailable. Ideally extension enumerations are code generated directly for the registry.

**Comment by Perksey** [comment]
Same applies as in #366

**Comment by oddhack** [comment]
Literally the only thing registry.py is intended for is associating extension numbers and names with extension spec files, and generating PHP include files for the HTML extension list in the index. I think it would take about 15 lines of Python added to the script to generate JSON output as well as PHP and if you wanted to propose such an MR, I'd take it.

We don't have any commitment to keeping the Python script around, though; it is just a tool for me when adding a new extension, is somewhat duplicative of gl.xml and potentially could be merged with that except that the labor cost involved would exceed maintaining the two different files.

**Comment by Perksey** [comment]
Having it built into the XML would be cool, but it seems like a lot of engineering effort for little gain.

**Comment by tsuoranta** [comment]
I ended up scanning and parsing extension texts directly instead. Only the specification texts have information about GLSL extension directives introduced by extensions.

For now, I have no need to do anything about `registry.py`.
