### ISSUE TITLE
Error in doc about cross product

### ISSUE THREAD

**Issue by xDRL64** [KhronosGroup/OpenGL-Registry#37]
hello I hope I can post this here.

there is an error on this page : 

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/cross.xhtml

at 'Description'

the last line of the example is :
x[0] × y[1] − y[1] × x[0]

but it should be :
x[0] × y[1] − y[0] × x[1]

by hoping it will help you

keep me in touch when you changed it, please

(sorry for my English, I'm learning)

**Comment by pdaniell-nv** [comment]
@xDRL64 Your suggested fix looks good. Would you mind making a PR?

**Comment by xDRL64** [comment]
hello, what is a PR?

________________________________
De : Piers Daniell <notifications@github.com>
Envoyé : vendredi 28 juillet 2017 17:40
À : KhronosGroup/OpenGL-Registry
Cc : xDRL64; Mention
Objet : Re: [KhronosGroup/OpenGL-Registry] Error in doc about cross product (#37)


@xDRL64<https://github.com/xdrl64> Your suggested fix looks good. Would you mind making a PR?

**Comment by pdaniell-nv** [comment]
By PR I meant a Pull Request with the fix. If you're unfamiliar with github we can do it.

**Comment by pdaniell-nv** [comment]
It was just pointed out to me that someone already did it:
https://github.com/KhronosGroup/OpenGL-Refpages/pull/24

**Comment by xDRL64** [comment]
yep I really unfamiliar with github. I prefer you do it. please thank you


________________________________
De : Piers Daniell <notifications@github.com>
Envoyé : lundi 31 juillet 2017 14:47
À : KhronosGroup/OpenGL-Registry
Cc : xDRL64; Mention
Objet : Re: [KhronosGroup/OpenGL-Registry] Error in doc about cross product (#37)


By PR I meant a Pull Request with the fix. If you're unfamiliar with github we can do it.

**Comment by xDRL64** [comment]
alright cool. now just still make this modification on this page :

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/cross.xhtml
where I discovered the wrong equation



________________________________
De : Piers Daniell <notifications@github.com>
Envoyé : lundi 31 juillet 2017 19:41
À : KhronosGroup/OpenGL-Registry
Cc : xDRL64; Mention
Objet : Re: [KhronosGroup/OpenGL-Registry] Error in doc about cross product (#37)


It was just pointed out to me that someone already did it:
KhronosGroup/OpenGL-Refpages#24<https://github.com/KhronosGroup/OpenGL-Refpages/pull/24>

**Comment by oddhack** [comment]
Generated HTML updated.
