### ISSUE TITLE
License of generated code

### ISSUE THREAD

**Issue by Dav1dde** [KhronosGroup/OpenGL-Registry#376]
I am the maintainer/author of [glad](https://github.com/Dav1dde/glad/), a code generation tool which uses the specs to generate Code for multiple languages, C/C++, Nim, Volt, D, Rust etc.

Now the issue has come up multiple times what license the generated code has:

* https://github.com/Dav1dde/glad/issues/101
* https://github.com/Dav1dde/glad/issues/253

To summarize the specs are Apache v2 licensed and would mean derivative work has to include the notice file, but the code is just loosely related to the original specs (completely transformed from XML to code). But on the other hand Vulkan explicitly contains this section:

> As an exception, if you use this Software to generate code and portions of
> this Software are embedded into the generated code as a result, you may
> redistribute such product without providing attribution as would otherwise
> be required by Sections 4(a), 4(b) and 4(d) of the License.

Could you clarify what the actual correct license for generated code is and if possible clarify this in the specs/specs repository?

From what I can see other projects that are also based on the XML specs also license the code generated not based on the Apache v2 (glbinding just says MIT). 

Libepoxy uses the wording `The generated code is derived from Khronos's xml files, which appear
under the following license` in their "COPYING".

**Comment by Dav1dde** [comment]
@oddhack thanks for the quick response, this is good to hear and aligns with what I thought/hoped.
I'll update my LICENSE/COPYING and readme to reflect this.

**Comment by Perksey** [comment]
Another interesting point (that doesn't necessarily need an answer, just something to think about): does Khronos even have the grounds to change the license for something like gl.xml? A file that has received many contributions from external contributors without any formal contribution license agreement assigning all IP to Khronos - theoretically you'd have to get every single contributor to agree to such a change, which is also one of the problems that the Linux kernel has accrued over the years.

Again, doesn't need an answer, just some food for thought :)
