### ISSUE TITLE
Typo in ARB_shader_storage_buffer_object

### ISSUE THREAD

**Issue by hanfling** [KhronosGroup/OpenGL-Registry#386]
Modify Table 6.71, Implementation Dependent Aggregate Shader Limits (cont.), p. 575

	    Get Value                         Type  Get Command    Minimum Value  Description                Sec. 
	    -----------------------           ----  -----------    -------------  -------------------------  -----
	    MAX_COMBINED_SHADER_OUTPUT   _    Z+    GetIntegerv    8              limit on active image      3.10.22
	      RESOURCES                                                           units, shader storage
	                                                                          blocks, and fragment outputs

Three spaces slipped before the _ in front of the line break inside the MAX_COMBINED_SHADER_OUTPUT_RESOURCES token, but they should be after the _

**Comment by Perksey** [comment]
Hey there! :wave: Thanks for reporting issues with the OpenGL registry! For minimal errors (such as these typos) we recommend opening a pull-request as it's the most productive way to get these errors fixed and in the spec, and/or comments regarding the issue. Thanks in advance!

**Comment by hanfling** [comment]
Okay here we go: https://github.com/KhronosGroup/OpenGL-Registry/pull/387

**Comment by Perksey** [comment]
This issue, along with #385, can now be closed

**Comment by hanfling** [comment]
Okay, I will try to remember this for future.
