### ISSUE TITLE
gl.xml enum group fixes

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#403]
- GL_TEXTURE_LOD_BIAS is missing from SamplerParameterF enum group
- GL_TEXTURE_BUFFER is missing from TextureTarget enum group
- GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS is missing from GetPName enum group
- GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS is missing from GetPName enum group
- GL_CONTEXT_PROFILE_MASK is GetPName is missing from GetPName enum group

These have supposedly harmless fix proposals in #397, #398 and #399.

**Comment by oddhack** [comment]
Fixed by #397, #398, #399.
