### ISSUE TITLE
Can we replace use of VertexBufferObjectParameter enum group for buffer queries in gl.xml?

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#404]
VertexBufferObjectParameter is used as enum group for buffer queries for example.
There are many other buffer types, so I would like to use BufferPNameARB instead.
Is there harm if we do this change?

Also, for pointer queries, BufferPointerNameARB would be correct.

Fix proposal in #400.

**Comment by Perksey** [comment]
> Fix proposal in #400.

No need to open an issue when you already have a PR open, just do a description of the change in the PR itself - that way there's less bloat!

Will look at your PRs now

**Comment by tsuoranta** [comment]
If you have mentioned this to me before, I have missed it, so good thing you mentioned it now. I will use PR only in the future. Thanks!

**Comment by oddhack** [comment]
Closed by #400.

Also, I believe that if you put e.g. "Fixes #404" as a standalone comment in an MR like #400, accepting that MR will auto-close the issue (I know gitlab does this, not certain about github).

**Comment by Perksey** [comment]
Yeah, if you put "closes #0" in the description issue 0 will automatically be closed upon merge.
