### ISSUE TITLE
Can we use strong vertex attrib pointer type enum groups?

### ISSUE THREAD

**Issue by tsuoranta** [KhronosGroup/OpenGL-Registry#406]
`glVertexAttribIPointer()` and `glVertexAttribLPointer()` currently use generic `VertexAttribPointerType` enum group for type parameter.
This generic group contains types such as float which are not allowed for these functions.
Can we use strong enum group types `VertexAttribIType` and `VertexAttribLType` instead?

Fix proposal in #402

**Comment by oddhack** [comment]
Closed by #402.
