### ISSUE TITLE
GL_ARB_buffer_storage spec ends error description mid way through a sentence

### ISSUE THREAD

**Issue by shadeslayer** [KhronosGroup/OpenGL-Registry#408]
When describing the error conditions in the GL_ARB_buffer_storage spec, this sentence ends half way through.

```
    INVALID_OPERATION is generated by MapBufferRange if MAP_PERSISTENT_BIT
    is included in <access> but MAP_PERSISTENT_BIT is not
    included in the buffer's storage flags, or if MAP_COHERENT_BIT is included
    in <access> but
```

I guess it should read

```
    or if MAP_COHERENT_BIT is included
    in <access> but MAP_COHERENT_BIT is not
    included in the buffer's storage flags
```

**Comment by Perksey** [comment]
Aha that's hilarious! Feel free to open a PR for issues like these with your suggested edits as pull requests are the most productive way to get feedback and opinions on small things like these.
