### ISSUE TITLE
Missing PDF for OpenGL 1.1

### ISSUE THREAD

**Issue by duzenko** [KhronosGroup/OpenGL-Registry#410]
This web folder has PDF's for all versions except 1.1
https://www.khronos.org/registry/OpenGL/specs/gl/
There's a .ps file but it's not web-friendly

Please add a .pdf version. An example conversion is here:
https://drive.google.com/file/d/1GpaQq0dOvuOcjTVBZ8afaxMAz3xckKCS/view?usp=sharing

**Comment by pdaniell-nv** [comment]
I'm not sure why the registry is like this, but @oddhack would know.

**Comment by oddhack** [comment]
> I'm not sure why the registry is like this, but @oddhack would know.

Nobody complained for 20 years so nothing was done until now.

**Comment by duzenko** [comment]
Thank you :)
