### ISSUE TITLE
question about GetActiveUniformBlockiv in gles spec3.2

### ISSUE THREAD

**Issue by TimeToWakeUp** [KhronosGroup/OpenGL-Registry#417]
Hi, I have a question about GetActiveUniformBlockiv api. In gles spec3.2, the input parameter pname of GetActiveUniformBlockiv can be set to UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER and UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER, but why did I not find the values of the UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER, UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER, and UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER macros in the header file of the official khronos gles opegl api?
![image](https://user-images.githubusercontent.com/34735089/89099635-657f3200-d423-11ea-8b86-f0590b854957.png)

**Comment by Perksey** [comment]
These enumerants are not included in the OpenGLES profile. Ensure you're using the correct documentation as the OpenGLES 3.2 Reference Pages don't seem to reference those enumerants at all.

https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glGetActiveUniformBlockiv.xhtml

**Comment by TimeToWakeUp** [comment]
> These enumerants are not included in the OpenGLES profile. Ensure you're using the correct documentation as the OpenGLES 3.2 Reference Pages don't seem to reference those enumerants at all.
> 
> https://www.khronos.org/registry/OpenGL-Refpages/es3/html/glGetActiveUniformBlockiv.xhtml

I'm pretty sure I'm using the right documents, the link to the document is here. 
https://www.khronos.org/registry/OpenGL/specs/es/3.2/es_spec_3.2.pdf
You can see these enumerants in this document.

**Comment by Perksey** [comment]
On what page? They're not referenced by the XML or Refpages, and I'm not familiar with the PDF structure but a quick Ctrl+F didn't pull much.

**Comment by pdaniell-nv** [comment]
> On what page? They're not referenced by the XML or Refpages, and I'm not familiar with the PDF structure but a quick Ctrl+F didn't pull much.

I think it's on page 108 of the ES 3.2 spec. It's probably a simple mistake they're missing from the headers.

@TimeToWakeUp can you propose a fix?

**Comment by dgkoch** [comment]
I don't think these were intended to be included in ES 3.2 since they were superseded by the program_interface_query variants.  The other stages had to continue being included for compatibility, but since TESS and GEOM shaders didn't exist in ES prior to ES 3.2 we opted to only add one way of querying information related to them.

**Comment by pdaniell-nv** [comment]
This is being handled internally at https://gitlab.khronos.org/opengl/API/-/issues/130. Closing this dupe.
