### ISSUE TITLE
Duplicate parameter names in api/GL/glcorearb.h

### ISSUE THREAD

**Issue by AlumiK** [KhronosGroup/OpenGL-Registry#421]
https://github.com/KhronosGroup/OpenGL-Registry/blob/e00a4645698f53314002582c7f267bb73d1dcd38/api/GL/glcorearb.h#L5261-L5273

There are two parameters named `offset` in line 5263 and 5265, which breaks my project.

**Comment by SunSerega** [comment]
Can confirm, breaks my bindings too. Looks like it these were added with new extension in https://github.com/KhronosGroup/OpenGL-Registry/commit/7b595e7097d523ff851aceb5edee7626b83f5194.

**Comment by oddhack** [comment]
Ouch! Yes, NV and I should each have caught that. I am asking them to fix ASAP; in the meantime I disabled the extension so it doesn't show up in the headers. Apologies.

@cubanismo the extension is owned by you and Carsten Rohde; could you please own correcting the spec and XML so there aren't two parameters named 'offset'?

**Comment by pdaniell-nv** [comment]
Sorry about that. Here is the fix: https://github.com/KhronosGroup/OpenGL-Registry/pull/422
