### ISSUE TITLE
Does OpenGL ES2.0 support math operation on negative 

### ISSUE THREAD

**Issue by smartadpole** [KhronosGroup/OpenGL-Registry#430]

**Comment by Perksey** [comment]
This is an incredibly vague question and not directly related to the OpenGL Registry itself. I recommend redirecting your question over to https://community.khronos.org where most OpenGL usage questions get answered - this repository is primarily for architecting the OpenGL API and its specifications.

**Comment by smartadpole** [comment]
thank you
