### ISSUE TITLE
[gl.xml] Question about type sizes and the usage of (unsigned) int

### ISSUE THREAD

**Issue by AndrewLKA** [KhronosGroup/OpenGL-Registry#434]
```xml
<type>typedef unsigned int <name>GLenum</name>;</type>
<type>typedef unsigned int <name>GLbitfield</name>;</type>
<type>typedef int <name>GLint</name>;</type>
<type>typedef unsigned int <name>GLuint</name>;</type>
<type>typedef int <name>GLsizei</name>;</type>
```
Shouldn't those be replaced with `khronos_int32_t` and `khronos_uint32_t` since OpenGL Specification says that those types should be exactly 32 bits while C and C++ specs makes it possible for those types to be 16 bits?

edit :
```xml
<type>typedef double <name>GLdouble</name>;</type>
<type>typedef double <name>GLclampd</name>;</type>
```
not sure about double either, maybe there should be some checks to check if double is exactly 64 bits?

**Comment by Lokathor** [comment]
I thought so when writing my parser/generator for gl.xml, but I'm a Rust programmer not a C programmer, so I figured it was just some C obscurity I wasn't aware of and mapped it all to `u32` / `i32`.

**Comment by oddhack** [comment]
I am not aware that anyone has ever tried to do a conformant OpenGL implementation on a platform with sizeof(int) != 4, but if a requirement emerges we'll deal with it at that time. LP64/LLP64 has ruled the world for many years and probably will for a long time to come.

**Comment by AndrewLKA** [comment]
I mean It looks very inconstant because other GL types do use the fixed size types
```xml
<type requires="khrplatform">typedef khronos_int8_t <name>GLbyte</name>;</type>
<type requires="khrplatform">typedef khronos_uint8_t <name>GLubyte</name>;</type>
<type requires="khrplatform">typedef khronos_int16_t <name>GLshort</name>;</type>
<type requires="khrplatform">typedef khronos_uint16_t <name>GLushort</name>;</type>
<type requires="khrplatform">typedef khronos_int32_t <name>GLclampx</name>;</type>
<type requires="khrplatform">typedef khronos_float_t <name>GLfloat</name>;</type>
<type requires="khrplatform">typedef khronos_float_t <name>GLclampf</name>;</type>
<type requires="khrplatform">typedef khronos_uint16_t <name>GLhalf</name>;</type>
<type requires="khrplatform">typedef khronos_int32_t <name>GLfixed</name>;</type>
<type requires="khrplatform">typedef khronos_intptr_t <name>GLintptr</name>;</type>
<type requires="khrplatform">typedef khronos_ssize_t <name>GLsizeiptr</name>;</type>
<type requires="khrplatform">typedef khronos_int64_t <name>GLint64</name>;</type>
<type requires="khrplatform">typedef khronos_uint64_t <name>GLuint64</name>;</type>
```
while those do not
```xml
<type>typedef unsigned int <name>GLenum</name>;</type>
<type>typedef unsigned char <name>GLboolean</name>;</type>
<type>typedef unsigned int <name>GLbitfield</name>;</type>
<type>typedef int <name>GLint</name>;</type>
<type>typedef unsigned int <name>GLuint</name>;</type>
<type>typedef int <name>GLsizei</name>;</type>
<type>typedef double <name>GLdouble</name>;</type>
<type>typedef double <name>GLclampd</name>;</type>
<type>typedef char <name>GLchar</name>;</type>
```
so I was wondering if there is any reason behind this ? even though the OpenGL specification says that that have to be "**exactly**" specific sizes (so I guess it would makes more sense to use fixed size types?)

**Comment by Perksey** [comment]
You're absolutely right, though a platform that doesn't use standard sizes for these types probably have other conformance issues waiting down the line. I'm not sure if this imposes a breaking change if PR'd in? (perhaps an ABI change but not one that will impact most users)

**Comment by AndrewLKA** [comment]
I guess I will just close the issue
>  but if a requirement emerges we'll deal with it at that time.

"If it isn't broken don't fix it!"

**Comment by Perksey** [comment]
Yeah leaving it be should be fine, as these types are pretty much always the size we expect. If a vendor experiences issues I guess we'll revisit but for now, as you said, if it ain't broke don't fix it!
