### ISSUE TITLE
basic opengl fuctions have been removed from GLext.h .

### ISSUE THREAD

**Issue by Aetherbase** [KhronosGroup/OpenGL-Registry#437]
Hello, i just noticed that basic functions glDrawArrays and glDrawElments have been removed from glext.h in the latest commit. how are the developers expected to go ahead with this?

**Comment by oddhack** [comment]
Are you referring to https://github.com/KhronosGroup/OpenGL-Registry/blob/master/api/GL/glext.h ? If so, which version of it are you using that includes these commands? They're core GL 1.1 APIs and as such are expected to be found in the platform-provided gl.h, not glext.h.

**Comment by Aetherbase** [comment]
I noticed this later. Thanks for the clarification. Closing.
