### ISSUE TITLE
GL_MAX_VARYING_COMPONENTS lists wrong alias string

### ISSUE THREAD

**Issue by Lokathor** [KhronosGroup/OpenGL-Registry#457]
In the following entry, the alias value is wrong:
```xml
<enum value="0x8B4B" name="GL_MAX_VARYING_COMPONENTS" alias="MAX_VARYING_FLOATS" group="GetPName"/>
```

It should be `GL_MAX_VARYING_FLOATS` rather than `MAX_VARYING_FLOATS`

**Comment by Perksey** [comment]
Fully agree, PR would be appreciated.

**Comment by pdaniell-nv** [comment]
@Lokathor are you willing and able to create a PR to fix this? It would be much appreciated. Thanks.

**Comment by Lokathor** [comment]
Yeah I'll try to remember to get to this soon.

**Comment by oddhack** [comment]
Fixed. Note, no effect on generated headers due to the way alias enums are emitted.
