### ISSUE TITLE
Compute Shader device support documentation 

### ISSUE THREAD

**Issue by davids91** [KhronosGroup/OpenGL-Registry#472]
Targeting GLES2, I've found myself in big blocks while implementing a certain massively parallelizable game logic (basically a grid based particle simulation for a sandbox game ). 

There are multiple choices to utilize GPUs, I considered using openCL, Compute shaders and in the hopes of supporting more devices ( especially in mobile space )  I also considered implementing the logic in fragment shaders. 

I actually have no valid reason why my first decision was to implement the logic in fragment shaders, it was just a gut feeling that t would be more widely supported, than compute shaders, even more so than openCL. I've also posted a SO question about it: 

https://gamedev.stackexchange.com/questions/192206/opengl-compute-shader-vs-fragment-shader-device-support

Unfortunately I found no documentation about the support of such technologies,  except for a SO Question here: 
https://stackoverflow.com/questions/60794310/how-to-use-compute-shaders-on-mobile-unity/63050577#comment119252711_63050577 

It stated that compute shader support was quite low. Despite the answer being from last year, I wouldn't think the situation have got any better. 

That would be fine, it's just that I can't seem to find any documentation about this, so I'm not sure whether or not I should dance around the roadblocks of implementing everything in a fragment shader, or I should just stop fighting windmills and use compute shaders or even openCL.. 

Any input on the topic is greatly appreciated, and I do hope I found the best media for such questions... 
Thank you in advance!

**Comment by pdaniell-nv** [comment]
The forums are probably a better place to ask this question: https://community.khronos.org/
