### ISSUE TITLE
Upcoming renaming of master -> main branch planned for late August 2021

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenGL-Registry#479]
@pdaniell-nv and other interested parties: heads-up that we propose to rename the default branch of this repository to 'main' in late August 2021, following emerging Khronos & github practice (for Khronos members, see internal khronos-general issue 106). This will have very little impact, although if you have a checked-out repository clone, you may want to follow the simple instructions github will pop up on the repository webpage describing how to do the same locally.

If there is a concern about this, please raise it here by 2021-08-23.

**Comment by Perksey** [comment]
Thanks for posting this!

I assume unlike the Vulkan rename that this will use the new GitHub functionality to facilitate this? We got caught out in a nasty way when Vulkan's repo was renamed.

**Comment by oddhack** [comment]
> Thanks for posting this!
> 
> I assume unlike the Vulkan rename that this will use the new GitHub functionality to facilitate this? We got caught out in a nasty way when Vulkan's repo was renamed.

Yes. The github renaming tool didn't exist last year when we did this for Vulkan-Docs and it handles a lot of forwarding and renaming stuff for us, so there should be relatively few cases where people are affected.

**Comment by oddhack** [comment]
Default branch has been renamed.
