### ISSUE TITLE
NV_depth_buffer_float2 is missing

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/OpenGL-Registry#488]
The `NV_read_depth_stencil` refers to the `NV_depth_buffer_float2`, which does not seem to exist in the registry.
https://github.com/KhronosGroup/OpenGL-Registry/blob/6eca3c2cdc3d1a1147302052e1f1f61cc487b79b/extensions/NV/NV_read_depth_stencil.txt#L40

So either the reference is invalid or the extension spec is missing.

**Comment by pdaniell-nv** [comment]
It appears this extension never saw the light of day and was internally abandoned. I think the extension spec needs to be updated to remove all references to it.

**Comment by dgkoch** [comment]
Agree - I'm not aware of it's existence either.
