### ISSUE TITLE
Missing gl prefix in gl.xml

### ISSUE THREAD

**Issue by NogginBops** [KhronosGroup/OpenGL-Registry#498]
#491 added `TexStorageAttribs2DEXT` and `TexStorageAttribs3DEXT` to `gl.xml` without the `gl` prefix.
This should be an error, and it's weird that it isn't caught when generating headers from the xml.

**Comment by Perksey** [comment]
@janharaldfredriksen-arm In your driver, has this been added with the `gl` prefix? If not, we should leave this as is or either change both the driver and the registry.

**Comment by janharaldfredriksen-arm** [comment]
Hi,
Our driver did actually add it with a `gl` prefix so we should just fix this in the registry. (The GLint is a typedef for int, so we could have fixed it without breaking any binary compatibility anyway.)
