### ISSUE TITLE
GLSL 4.50: layout qualifier table is missing `offset` when applied to atomic counters.

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#5]
Chapter 4.4 in GLSL 4.50 (revision 6) is missing an entry in the layout qualifier table. Atomic counters can use the `offset` qualifier (4.4.6.1), but it is not listed in the table as being valid.

**Comment by johnkslang** [comment]
This is now fixed internally in Revision 7 of GLSL 4.5.

**Comment by pdaniell-nv** [comment]
Closing.
