### ISSUE TITLE
[OPENGL] GLEnum.Float32UnsignedInt248Rev missing from PixelType enum

### ISSUE THREAD

**Issue by Kermalis** [KhronosGroup/OpenGL-Registry#500]
Hello, I was told to create this issue by the Silk.NET team.

The issue is basically the title, that value is not in the PixelType enum. It'd be useful here:
```cs
gl.TexImage2D(TextureTarget.Texture2D, 0, InternalFormat.Depth32fStencil8, (uint)size.X, (uint)size.Y, 0, PixelFormat.DepthStencil, GLEnum.Float32UnsignedInt248Rev, null);
```

**Comment by pdaniell-nv** [comment]
@Kermalis would you like to propose a [PR](https://github.com/KhronosGroup/OpenGL-Registry/pulls)?
