### ISSUE TITLE
Why OpenGL not supporting multiple EBO (ELEMENT buffer Object) for a given VAO

### ISSUE THREAD

**Issue by abmajith** [KhronosGroup/OpenGL-Registry#503]
I am learning our OpenGL API, what I felt while learning OpengL is to render a complex obj model. We could save lot of CPU memory and computation, if we allow to bind two separate EBO's (one for vertex position and one for normal position) to a VAO. Because, while extracting the obj file information at the moment, I need to produce lot of unique vertices data (in the combined position and normal spaces).

Instead of doing this, let say one EBO to map the vertex position (in VBO vertex position array), one EBO to map the normal position (in VBO normal position array), and can extend to UV textures too.

Is there any fundamental limitation in GPU for not allowing more than one EBO for a given VAO?

**Comment by pdaniell-nv** [comment]
It's likely most/all GPUs can only source one index buffer per draw.

**Comment by pdaniell-nv** [comment]
Closing since this isn't something any current GPUs support. Please reopen if you have any follow up. Thanks.
