### ISSUE TITLE
Conformance Tests

### ISSUE THREAD

**Issue by shenyun0116** [KhronosGroup/OpenGL-Registry#512]
khronos has launched The Vulkan SC & OpenGL SC API Specification. Does the group provide the Conformance Tests?

**Comment by dgkoch** [comment]
This really isn't the correct forum for this question (this is the registry for OpenGL extensions). 

However the Vulkan SC conformance tests are available as part of the VK-GL-CTS Project https://github.com/KhronosGroup/VK-GL-CTS
