### ISSUE TITLE
GetDebugMessageLogAMD takes GLint* argument instead of GLenum*

### ISSUE THREAD

**Issue by NogginBops** [KhronosGroup/OpenGL-Registry#516]
The function `GetDebugMessageLogAMD` from `GL_AMD_debug_output` is defined as follows: 
```c
uint GetDebugMessageLogAMD(uint count,
                               GLsizei bufsize,
                               GLenum* categories,
                               GLuint* severities,
                               GLuint* ids,
                               GLsizei* lengths, 
                               GLchar* message);
```

Shouldn't the `severities` argument be of type `GLenum`? 
This would match every other definition of this function from other extensions.

As they are `typedef`ed as the same type is it possible to change this?

**Comment by rpatlega** [comment]
Yes, severities should be processes as enum paramters.
For details refer the extension- 
https://www.khronos.org/registry/OpenGL/extensions/AMD/AMD_debug_output.txt


** The application can query the number of messages currently in the log by
    obtaining the value of DEBUG_LOGGED_MESSAGES_AMD, and can get the contents
    of those messages using the command:

        uint GetDebugMessageLogAMD(uint count,
                                   sizei logSize,
                                   enum* categories,
                                   enum* severities,
                                   uint* ids,
                                   sizei* lengths,
                                   char* messageLog);

    This function will fetch as many messages as possible from the message
    log up to <count> in order from oldest to newest, and will return the
    number of messages fetched.  Those messages that were fetched will be
    removed from the log.  The value of <count> must be greater than zero and
    less than MAX_DEBUG_LOGGED_MESSAGES_AMD or otherwise the error
    INVALID_VALUE will be generated.  The value of <count> can be larger than
    the actual number of messages currently in the log.  If <messageLog> is not
    a null pointer, then the string representations of all fetched messages will
    be stored in the buffer <messageLog> and will be separated by null-
    terminators.  The maximum size of the buffer (including all null-
    terminators) is denoted by <logSize>, and strings of messages within <count>
    that do not fit in the buffer will not be fetched.  If <logSize> is less
    than zero, the error INVALID_VALUE will be generated.  If <messageLog>
    is a null pointer, then the value of <logSize> is ignored.  The
    categories, severity levels, IDs, and string representation lengths of all
    (up to <count>) removed messages will be stored in the arrays <categories>,
    <severities>, <ids>, and <lengths>, respectively.  The counts stored in the
    array <lengths> include the null-terminator of each string.  Any and all of
    the output arrays, including <messageLog>, are optional, and no data is returned
    for those arrays that are specified with a null pointer.  To simply delete up
    to <count> messages from the message log and ignoring, the application can call
    the function with null pointers for all output arrays.  The error
    INVALID_OPERATION will be generated by GetDebugMessageLogAMD if it is
    called in a non-debug context.**

**Comment by rpatlega** [comment]
This function will return the following severity levels to parameter GLuint* severities.
#define GL_DEBUG_SEVERITY_HIGH_AMD        0x9146
#define GL_DEBUG_SEVERITY_MEDIUM_AMD      0x9147
#define GL_DEBUG_SEVERITY_LOW_AMD         0x9148

Refer to [specification ]( https://www.khronos.org/registry/OpenGL/extensions/AMD/AMD_debug_output.txt)for details - 

The GLuint and GLenum are typecasted from unisigned int, so should not be any concerns of conversion from application side.
typedef unsigned int    GLenum;
typedef unsigned int    GLuint; 

So application will get the Glenum as expected here. The IHV vendors will be returning severity levels as mentioned above.

**Comment by NogginBops** [comment]
This is more of a issue is more in relation to #517. 
I know how the function works and how it's not a problem in c.
But it's a problem in many bindings generators for other programming languages.

**Comment by oddhack** [comment]
I suggest trying to contact Jaakko Konttinen, who is listed as the extension contact. I believe they're still at AMD, 12 years on. I am fairly sure none of the other listed contributors to the extension are still at AMD but if you can't reach the contact, we can ask around inside Khronos to see if anyone at AMD feels ownership over this extension.

**Comment by rpatlega** [comment]
We have approved extension - GL_ARB_ debug_output.txt
https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_debug_output.txt

 which has listed these parameters to enum* severities.
 uint GetDebugMessageLogARB(uint count,
                               sizei bufSize,
                               enum* sources,
                               enum* types,
                               uint* ids,
                               enum* severities,
                               sizei* lengths, 
                               char* messageLog);

We have discussed this in working group, and we dont have issues to keep it to GLuint * or change to GLenum* severities.

**Comment by pdaniell-nv** [comment]
To be clear, the WG doesn't have an issue with the GL_AMD_debug_output extension changing from GLuit to GLenum if that's acceptable to AMD.

**Comment by rpatlega** [comment]
Yes, this is acceptable to AMD.
