### ISSUE TITLE
Link to GLSL_ES_Specification_1.0.pdf is 404ing on WebGL 1.0 spec.

### ISSUE THREAD

**Issue by gregtatum** [KhronosGroup/OpenGL-Registry#52]
On the [WebGL 1 spec page](https://www.khronos.org/registry/webgl/specs/latest/1.0/#refsGLES20GLSL) (and on other non-Khronos reference sites), the following link is 404ing:

> [GLES20GLSL]
>    The OpenGL® ES Shading Language Version 1.00, R. Simpson, May 2009.

It is pointing to:

https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.0.pdf

**Comment by TobiasHector** [comment]
@Khronoswebmaster is this something you can take a look at adding a redirect for?

**Comment by Khronoswebmaster** [comment]
I believe this is an old bug as it works fine now. Please verify and close if okay.

**Comment by TobiasHector** [comment]
Ah yes it looks like there was simply a missing "0" in the link in the WebGL spec, so presumably this link has always been incorrect (thus is just a bug in the WebGL spec). Closing - @gregtatum if you believe this to still be an issue elsewhere, please reopen with comment.

**Comment by gregtatum** [comment]
The link works now, thank you!
