### ISSUE TITLE
wgl.xml has incorrect const pointers

### ISSUE THREAD

**Issue by cstanfill** [KhronosGroup/OpenGL-Registry#525]
I took a crack at writing my own GL loader, then extended it to GLX and WGL, but when generating the core API functions from WGL, my generated header ended up with declaration conflicts on just a few functions from wingdi.h (extensions seem to work fine). I can't find anyone else discussing this, but the wingdi.h types make more sense so I think this is just a bug in the xml.

The functions are:
* DescribePixelFormat
* GetEnhMetaFilePixelFormat
* wglDescribeLayerPlane
* wglGetLayerPaletteEntries

and in each case the last parameter is an out pointer which is marked const in the xml.

**Comment by oddhack** [comment]
If you would like to propose a PR to wgl.xml I expect we wouldn't have any problem accepting it, since we only generate wglext.h for extensions and expect people to rely on Microsoft's headers for core WGL functionality.

**Comment by NogginBops** [comment]
This should be fixed with #527

**Comment by oddhack** [comment]
Agreed - closing this.
