### ISSUE TITLE
glIndexFuncEXT takes float parameter in extension and GLclampf in gl.xml

### ISSUE THREAD

**Issue by NogginBops** [KhronosGroup/OpenGL-Registry#542]
In [EXT_index_func.txt](https://github.com/KhronosGroup/OpenGL-Registry/blob/main/extensions/EXT/EXT_index_func.txt) `glIndexFuncEXT` is defined as
```c
void IndexFuncEXT (enum func, float ref)
```
while gl.xml specifies it as (with the second parameter as `GLclampf`)
```xml
<command>
    <proto>void <name>glIndexFuncEXT</name></proto>
    <param group="IndexFunctionEXT"><ptype>GLenum</ptype> <name>func</name></param>
    <param kind="ColorIndexValue"><ptype>GLclampf</ptype> <name>ref</name></param>
</command>
```

One of the two documents should be updated to contain the correct definition of the function.

**Comment by NogginBops** [comment]
I've now realized that it's `GLclampf` instead of `GLfixed` which means this isn't really an issue as the `GLclampf` is defined as `float`. I'm closing this as the `GLclampf` typedef probably didn't exist in the 1.1 spec on which the extension is written against.

If this is something that Khronos feels should done about this then feel free to reopen the issue.

**Comment by Perksey** [comment]
~~Isn't this fine given the differing purposes of the two documents? i.e. the extension specification serves to be an illustrative source for the implementation of OpenGL, whereas the XML/C headers are meant to be the authoritative source for the actual API. For instance, ``GLclampf` is a `typedef` for a `float` but the specification document is abstracted away from the granular typedefs that you'd find in C. I feel like as long as the specification is illustrative of what the actual ABI (i.e. it's not *horribly* wrong) is it's not too much of an issue.~~

EDIT: issue has been closed :)
