### ISSUE TITLE
Min/Max function changes lower bits of float mantissa in shaders

### ISSUE THREAD

**Issue by chiraagChakravarthy** [KhronosGroup/OpenGL-Registry#553]
glsl version: 330
lwjgl version: 4.5
gpu: Intel HD Graphics 6000 1536 MB
os: macOS Sierra 10.12.6

When using the min/max function in a shader, the lower bits of the mantissa changes and creates artifacts in rare cases, but when using the mix function in a similar way it doesn't.
```
float a = (some value);
float b = (some value);
float c = min(a, b);
float d = mix(a, b, b<a);
//in some cases c!=d

```
In the example above, when c and d are different, d is correct and c is slightly off.

**Comment by pdaniell-nv** [comment]
Since this is an implementation bug, and no OpenGL/ES spec change is needed, closing.
