### ISSUE TITLE
glNamedFramebufferTextureMultiviewOVR missing from XML

### ISSUE THREAD

**Issue by patrickdown** [KhronosGroup/OpenGL-Registry#562]
NamedFramebufferTextureMultiviewOVR defined in the multiview extension https://registry.khronos.org/OpenGL/extensions/OVR/OVR_multiview.txt is missing from the XML.

[[ If OpenGL 4.5 or ARB_direct_state_access is supported ]]

void NamedFramebufferTextureMultiviewOVR( uint framebuffer, enum attachment,
                                              uint texture, int level,
                                              int baseViewIndex, sizei numViews );

**Comment by pdaniell-nv** [comment]
@patrickdown would you mind contributing a fix here: https://github.com/KhronosGroup/OpenGL-Registry/pulls. Thank you.

**Comment by JacobGrenier** [comment]
> NamedFramebufferTextureMultiviewOVR defined in the multiview extension https://registry.khronos.org/OpenGL/extensions/OVR/OVR_multiview.txt is missing from the XML.
> 
> [[ If OpenGL 4.5 or ARB_direct_state_access is supported ]]
> 
> void NamedFramebufferTextureMultiviewOVR( uint framebuffer, enum attachment,
>                                               uint texture, int level,
>                                               int baseViewIndex, sizei numViews );
> 
>

**Comment by oddhack** [comment]
@JacobGrenier @patrickdown see #608.
