### ISSUE TITLE
Source text or machine-readable data for state tables

### ISSUE THREAD

**Issue by hikari-no-yume** [KhronosGroup/OpenGL-Registry#571]
The state tables section of the OpenGL specification is a very handy reference, but so far as I can tell it's only available in PDF form. Is there no machine-readable (e.g. XML) form somewhere, or even something like LaTeX source? It would be very useful when writing tooling. In particular, I'm interested in doing API translation, and with a machine-readable form I could have a script automatically compile common subsets, for example. (I asked about this on a social media site and [someone suggested making this issue](https://social.noyu.me/@hikari/statuses/01GWW1CW8SHYDYPX8YH6516EHV).)

**Comment by hikari-no-yume** [comment]
> The WG might be OK with releasing just the state table appendix LaTeX

If so, I'd really appreciate it!

> If we were to do this you should not expect much help interpreting it, nor for it to be buildable as a standalone document, because we're not putting many cycles into GL these days.

That's no problem for me. I'm sure I could figure it out on my own.

> Alternatively, you can 'pdfgrep .' on relevant pages of the PDF to extract the text followed by some hand-massaging of the result.

I definitely could attempt this, but my fear is it would be a very fragile solution at best.

**Comment by oddhack** [comment]
> Oh, in case anything does come of this: is there distinct source for each OpenGL version, and do you think it would be more effort to provide the state tables for all versions, not just the latest version?

They are separate branches in our internal development tree though it's increasingly rare that we would update anything but the current 4.6 spec (and it's unlikely there will ever be an updated core version in the future).

I don't think there's a lot of value in the older tables and would prefer not to have to go dig them all up if the WG does decide to proceed with this. gl.xml describes which state variables are introduced with each version of the API although there are occasionally updates in the limits between revisions of the API.

**Comment by oddhack** [comment]
Also, looking at your touchHLE issue, it sounds like you may want the GLES state tables, instead of or in addition to the GL ones?

**Comment by hikari-no-yume** [comment]
> They are separate branches in our internal development tree though it's increasingly rare that we would update anything but the current 4.6 spec (and it's unlikely there will ever be a (edit: new) core version in the future).

I see, thanks for the insight.

> Also, looking at your touchHLE issue, it sounds like you may want the GLES state tables, instead of or in addition to the GL ones?

Yes, that's right. For my current application, I'm interested in the intersection of OpenGL ES 1.1 and the OpenGL compatibility profile (notionally OpenGL 2.1). Since OpenGL ES isn't a strict subset of OpenGL, it would be useful to have state tables for both.

> I don't think there's a lot of value in the older tables and would prefer not to have to go dig them all up if the WG does decide to proceed with this. gl.xml describes which state variables are introduced with each version of the API although there are occasionally updates in the limits between revisions of the API.

I think the gl.xml approach means you could skip most of the old versions, yeah. At least for my application, I don't think the limit changes matter, it's really the parameter names and type information I'm after.

The only caveat I can see is that major versions sometimes remove old features:

* Is the GL 4.6 compatibility profile a superset of all the previous ones? If so, I think its state tables are all I need on the GL side.
* GLES 1 and GLES 2/3 are almost completely incompatible, and it happens to be GLES 1 I am interested in, so I'd want the GLES 1.1 state tables.

I don't have an immediate use for them, but for completeness, I'm sure the GL 4.6 core profile and GLES 3.2 would be useful to others.

Someone tell me if I'm forgetting some compatibility break.

**Comment by pdaniell-nv** [comment]
We discussed this in the OpenGL/ES working group and we don't object to making the table source public. I'll leave it to @oddhack to figure out the details on how best to do this to meet your needs and not be too much work.

**Comment by hikari-no-yume** [comment]
Thanks for taking the time to consider it!

**Comment by oddhack** [comment]
I'm attaching the 
[statetables.zip](https://github.com/KhronosGroup/OpenGL-Registry/files/11334411/statetables.zip) LaTeX markup for the current GL and ES spec state table appendices. They are not standalone documents as they use some formatting macros whose definitions are not included and which I really can't justify the time to extract from the rest of the spec build, but they are fairly obvious. N.b. the '\ifnum\specdep=1' macros surround material that only goes in the compatibility specification build.

**Comment by hikari-no-yume** [comment]
Thank you! To confirm, are these for OpenGL 4.6 and OpenGL ES 3.2, respectively? Would you be able to provide OpenGL ES 1.1 as well?

**Comment by oddhack** [comment]
> Thank you! To confirm, are these for OpenGL 4.6 and OpenGL ES 3.2, respectively? Would you be able to provide OpenGL ES 1.1 as well?

Yes. I updated the zipfile attachment above to include that. I cannot provide the tables for all older versions of the specifications, however.

**Comment by oddhack** [comment]
> I noticed the OpenGL ES 1.1 LaTeX doesn't include the introduction text (“The tables on the following pages indicate …”) and the table explaining the type codes. Was that intended?

In the sense that the ES 1.1 spec is many years older than the other two and periodic reformatting / restructuring of the document happened, yes. Glad this is working out for you.

**Comment by hikari-no-yume** [comment]
Here's what came of my efforts:

* Nice HTML output: https://hikari.noyu.me/etc/gl-state-tables.html
* Parser source: https://github.com/hikari-no-yume/OpenGL-state-table-parser
* Announcement post: https://social.noyu.me/@hikari/statuses/01H5MDER8FVKRM889YYVKCFB2K

As expected, it was far from trivial to parse, but with a few days' effort I got some of the fields into a good shape. It's still a work in progress and can't parse everything, but it parses enough that it felt worth releasing.

This will be my last comment in this ticket. Thanks again for releasing the sources!
