### ISSUE TITLE
XID type is missing from glx.xml

### ISSUE THREAD

**Issue by codingatc** [KhronosGroup/OpenGL-Registry#572]
The other types coming from X11 are present such as `Display`. At minimum I think `XID` should be added to the xml as a placeholder like the other types. I am happy to add a PR if there is agreement on the fix.

**Comment by oddhack** [comment]
Sure, that's fine. Just add it to the dummy placeholder section like the others (as long as you're there, it should say "X / OpenGL types", not just "X types" in the comment, for completeness).
