### ISSUE TITLE
Missing glx.h

### ISSUE THREAD

**Issue by jamesdolan** [KhronosGroup/OpenGL-Registry#59]
api/GL/glx.h is missing but all other generated headers (including glxext.h) are in place.

**Comment by oddhack** [comment]
There is an experimental target for glx.h in genheaders.py, but we've never fully tested or deployed it, expecting people would use the version supplied with the OS or Mesa implementation. New GLX extensions go in glxext.h so glx.h itself has not needed change in many years. You are welcome to generate the file yourself and suggest fixes for anything that seems wrong with it.
