### ISSUE TITLE
GL_KHR_texture_compression_astc_hdr interactions with desktop OpenGL

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#6]
After looking at this specification, it is not clear how it interacts with features of desktop OpenGL that are not present in OpenGL ES 3.0+.

For example, in desktop GL, you are allowed to use `glCompressedTexSubImage*D` to modify any arbitrary rectangle, so long as the specified rectangle is along the block size boundary for the format. But in ES 3.0, you're only allowed to modify a rectangle that ends at the top right; the `offset`+`size` in each dimension must be equal to the total size in that dimension.

The extension uses the ES 3.0 wording; should we take that to mean that, if the extension is exposed to desktop GL, that the ASTC formats would have the same limitation?

For another example, destkop OpenGL allows you to create 1D textures and 1D array textures. Can you use ASTC for these?

**Comment by TobiasHector** [comment]
@NicolBolas could you raise a separate issue for your "other important point" at the bottom? That should probably be tracked separately.

**Comment by NicolBolas** [comment]
@TobiasHector : Done. See issue #8

**Comment by TobiasHector** [comment]
Thanks!
