### ISSUE TITLE
Wrong texture environment tables in specifications for GL versions 1.3, 1.4 and 1.5

### ISSUE THREAD

**Issue by mariob92** [KhronosGroup/OpenGL-Registry#604]
The tables 3.22 and 3.23 for the texture environment functions in the three mentioned specification PDFs (glspec13.pdf, glspec14.pdf, glspec15.pdf) seem to be wrong.

They are referencing C<sub>f</sub> and A<sub>f</sub> instead of C<sub>p</sub> and A<sub>p</sub>. In glspec20.pdf the tables are fixed.

**Comment by oddhack** [comment]
You are doubtless correct, but we do not do bugfixes to old GL specifications. They are just in the registry for historical completeness.
