### ISSUE TITLE
Typo in WGL_ARB_pixel_format_float

### ISSUE THREAD

**Issue by NogginBops** [KhronosGroup/OpenGL-Registry#616]
Should be `WGL_TYPE_RGBA_FLOAT_ARB` instead of `WGL_TYPE_RGBA_FLAOT_ARB`.
https://github.com/KhronosGroup/OpenGL-Registry/blob/5466009a38991f5ea5c2009105bd83f19fe49979/extensions/ATI/WGL_ATI_pixel_format_float.txt#L221

**Comment by oddhack** [comment]
Thanks!
