### ISSUE TITLE
GL_GLEXT_VERSION missing in ES2 and ES3 headers

### ISSUE THREAD

**Issue by emersion** [KhronosGroup/OpenGL-Registry#617]
`api/GL/glext.h` exposes `GL_GLEXT_VERSION`. However, this symbol is missing from GLES2/GLES3 headers. This makes it difficult to check for the version of the headers programmatically (e.g. to ensure the headers are new enough to contain required extensions).

**Comment by zmike** [comment]
WG 2024-07-17: Adding to ES headers is approved. Please create a pull request.
