### ISSUE TITLE
NV_pixel_buffer_object missing from gl.xml, header files

### ISSUE THREAD

**Issue by shannonwoods** [KhronosGroup/OpenGL-Registry#63]
It looks like the symbols for NV_pixel_buffer_object never made it into the XML file, and by extension are missing from gl2ext.h.

**Comment by oddhack** [comment]
I am encouraging a self-service model now that we're on github. If someone from NV (or really, anyone else) wants to make the gl.xml changes and regenerate the headers, I'll verify it and merge to master, otherwise this may take a while.

**Comment by dgkoch** [comment]
Done in PR #84 (which will of course conflict with PR #83)
