### ISSUE TITLE
Clarification wanted: EGL_EXT_image_dma_buf_import for single buffer multi plane case

### ISSUE THREAD

**Issue by yuq** [KhronosGroup/OpenGL-Registry#636]
Hi, I'm recently working on AMD GPU to export modifier for EGLImage by `EGL_MESA_image_dma_buf_export`:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/31658

Then I found some AMD modifiers have 2 or 3 planes, but they use the same buffer with different offsets. `EGL_MESA_image_dma_buf_export` has words on this case to just set `export_fd[1]` and `export_fd[2]` to `-1`. But I can't find in `EGL_EXT_image_dma_buf_import` how to set `import_fd[1]` and `import_fd[2]`. We have some choices listed bellow:

1. set them to `-1` too
2. pass `export_fd[0]` to all of them
3. skip `EGL_DMA_BUF_PLANE1_FD_EXT` and `EGL_DMA_BUF_PLANE2_FD_EXT`

**Comment by fooishbar** [comment]
It's option 2, as can already be seen in wide use on several vendors.

**Comment by yuq** [comment]
Thanks for the clarification.

**Comment by yuq** [comment]
Thanks for the clarification.
