### ISSUE TITLE
Provide TeX sources for specifications

### ISSUE THREAD

**Issue by The-Minecraft-Scientist** [KhronosGroup/OpenGL-Registry#638]
it would be really nice for the public/normal users to have access to the TeX sources for the GL specs, as the pre-rendered PDFs have some issues:
* lots of wasted white space (large indent)
* certain underscore characters translating to spaces in the text layer
* page breaks only get in the way when reading digitally (more wasted white space)

Providing the TeX sources would allow the community to address those issues by itself, as well as allow those who'd like to to modify the typesetting for accessibility or comfort (e.g. switching to a dsylexia-friendly font or changing the background color).

**Comment by oddhack** [comment]
Unfortunately, we are not going to be doing this. It would be quite a lot of work to prepare the specification sources for public release, of interest to few people, and OpenGL is essentially a legacy activity within Khronos at the moment. We do try to make accessibility changes in our active specs, like Vulkan, and people can contribute to those on github. I'm sorry not to have better news.
