### ISSUE TITLE
glGetShaderPrecisionFormat precision parameter has wrong len attribute

### ISSUE THREAD

**Issue by Frassle** [KhronosGroup/OpenGL-Registry#78]
In xml/gl.xml the parameter data for "precision" does not match what the OpenGL spec says. The xml has len=2:
`<param len="2"><ptype>GLint</ptype> *<name>precision</name></param>`
While the spec for precision reads "Specifies the address of an integer into which the numeric precision of the implementation is written.".
Thus I'd expect len to be 1.

**Comment by pdaniell-nv** [comment]
@Frassle Your fix sounds good. Would you mind making a PR?
