### ISSUE TITLE
GL_KHR_texture_compression_astc_ldr/hdr mipmap size restrictions

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#8]
The GL_KHR_texture_compression_astc_ldr/hdr extension seems to say that ASTC-compressed textures must have each mipmap layers' width and height be multiples of block sizes. Is this intended, as no other compressed format works that way. Even ES 3.0 has no language stating that its compressed formats are required to be multiples of block sizes. Not only that, it doesn't fit the wording for `glTexStorage*D`, which explains those commands in terms of `glTexImage*D`. And there, nothing compensates for having to use sizes that are multiples of block boundaries on mipmaps.

**Comment by pdaniell-nv** [comment]
Thanks for the bug report. We have filed an internal issue to address the problem.

**Comment by janharaldfredriksen-arm** [comment]
I don't think the spec means to say that that mipmap layers's width and height need to be multiples of the block size. (The image size must obviously be a multiple of the block size, but the dimensions shouldn't have to be.)

I think what the spec is trying to say is that:
 - the dimensions passed to CompressedTexImage* must be a multiple of the block size.
 - the dimensions passed to CompressedTexSubImage* must be a multiple of the block size _or_ the entire level.

The first condition is what's described by:
> The width and height of each sub-image must be a multiple of the block size for the format, shown in the same table."

The second condition is what's described by:
> width is not a multiple of the format's block width, and width + xoffset is not equal to the value of TEXTURE_WIDTH.

Note the ", and" and that TEXTURE_WIDTH will return the width of a given level.

Does that help clear things up?

**Comment by NicolBolas** [comment]
> The width and height of each sub-image must be a multiple of the block size for the format, shown in the same table."

I did some more research in ES, and I found that this limitation really has been there since at least 3.0 if not earlier.

But that doesn't explain how `glTexStorage2D` works. Consider this error (OpenGL ES 3.2):

> An `INVALID_OPERATION` error  is  generated  if `levels` is  greater  than floor(log<sub>2</sub>(max(width, height))) + 1

So if the block size is 4x4, and I create a 32x16 texture, I could only create 3 mipmap layers if I use `glCompressedTexImage2D`. But according to the above restriction, I should be able to set `levels` to 5 with no problems.

So there is still a contradiction here. If `glTexStorage` is implemented in terms of `gl(Compressed)TexImage`, then there must be a limitation on `glTexStorage`'s `levels` parameter based on the minimum mipmap size for a particular `width`/`height`/`depth` and `internalformat`.

And the following error, which applies to all forms of `glTexStorage*` functions, doesn't quite cover it:

> An `INVALID_OPERATION` error is generated if `internalformat` is a compressed texture format and there is no `imageSize` for which the corresponding `CompressedTexImage*` command would have been valid.

Nothing here says anything about `levels` requesting more mipmap levels than the compressed format is permitted to have, based on its block restrictions.

----

> the dimensions passed to CompressedTexSubImage* must be a multiple of the block size or the entire level.

The specification says more than that:

>> width is not a multiple of the format's block width, and width + xoffset is not equal to the value of TEXTURE_WIDTH.

I noted this bug in #6. Namely, this requires that `width` + `xoffset` must be *equal to* the texture's width.

Which means that all uploads have to be right-justified: you must copy into the right-most column of data. And top-most row.

Now this has actually been a long-standing limitation of OpenGL ES specification since at least 3.0. Which is why it's part of bug #6 (which is about desktop GL's interactions with the ASTC extension), not this one ;)

**Comment by NicolBolas** [comment]
> I don't think the spec means to say that that mipmap layers's width and height need to be multiples of the block size.
>...
> the dimensions passed to CompressedTexImage* must be a multiple of the block size.

But the dimensions passed to that function are what *defines* each mipmap level's width and height. So if the `width` and `height` parameters are restricted to multiples of the block size for *any call* to that function, you won't be able to call it for mipmap levels unless they too are a multiple of the block size.

If your base level is 60x60 with a 4x4 block size, that's legal and you can call `glCompressedTexImage`. But calling `glCompressedTexImage*` for mipmap level 1 with 30x30 is not legal, for the same reason as if you were creating mipmap level 0.

If the intent of the specification is to allow a 30x30 size for mipmap level 1, then the current wording does not permit that. Though I have discovered that the current wording has been there since GL ES 3.0, so it's not something specific to ASTC.

Furthermore, the current wording does not explain how `glTexStorage` works. It is supposed to be defined in terms of `gl(Compressed)TexImage` calls. But the limitation on `levels` does not take into account the size limitation on the texture's block size. In the above case of a 60x60 texture, `glTexStorage` says that it's OK for me to pass 6 to `levels`, but if I were using `glCompressedTexImage` directly, I could only create the base level.

That inconsistency does lend weight to your idea of what the _intended_ behavior is (restrict only the size of level 0). But that doesn't change the fact that the wording doesn't agree.

**Comment by janharaldfredriksen-arm** [comment]
Thanks, you're right.

We'll need to look at how we can resolve this. We should at least clarify, but whether we can change the described behavior to make more sense depends on what everyone already implements.

**Comment by TobiasHector** [comment]
We resolved that nobody has this restriction in their implementation, so is a spec bug. @janharaldfredriksen-arm will propose a PR to remove the offending sentence.
