### ISSUE TITLE
GL_OES_draw_elements_base_vertex: Confusion between OES and EXT suffix for glMultiDrawElementsBaseVertex

### ISSUE THREAD

**Issue by imirkin** [KhronosGroup/OpenGL-Registry#81]
The [spec](https://github.com/KhronosGroup/OpenGL-Registry/blob/master/extensions/OES/OES_draw_elements_base_vertex.txt) has it as glMultiDrawElementsBaseVertexEXT (since it's attached to EXT_multi_draw_arrays which has no OES equivalent). However the gl.xml file has

    <command name="glMultiDrawElementsBaseVertexOES" comment="Supported only if GL_EXT_multi_draw_arrays is supported"/>

and

        <command>
            <proto>void <name>glMultiDrawElementsBaseVertexOES</name></proto>
            <param group="PrimitiveType"><ptype>GLenum</ptype> <name>mode</name></param>
            <param len="COMPSIZE(drawcount)">const <ptype>GLsizei</ptype> *<name>count</name></param>
            <param group="DrawElementsType"><ptype>GLenum</ptype> <name>type</name></param>
            <param len="COMPSIZE(drawcount)">const void *const*<name>indices</name></param>
            <param><ptype>GLsizei</ptype> <name>primcount</name></param>
            <param len="COMPSIZE(drawcount)">const <ptype>GLint</ptype> *<name>basevertex</name></param>
            <alias name="glMultiDrawElementsBaseVertex"/>
        </command>

It may be worth noting that mesa is also accidentally providing the OES suffix for that command. The question is whether to change the gl.xml or to change the extension spec.

**Comment by dgkoch** [comment]
Yes it should be EXT, would you like to file a PR to fix it?

**Comment by imirkin** [comment]
@dgkoch Sure, I can try to do it tonight. Should I try to regenerate the headers too, or do you guys want to take care of that? To be clear, I'm doing s/OES/EXT/ on those two places and that's it?
