### ISSUE TITLE
ARB_gl_spirv mentions variables that don't exist in GLSL

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/OpenGL-Registry#90]
Specifically, it talks about `gl_Vertex/InstanceIndex`, rather than `gl_Vertex/InstanceID`. However much I might *wish* that we had the former instead of the latter, GLSL sadly does not. Well, except for the KHR_vulkan_glsl variation, but that's a different matter. Indeed, the ARB_gl_spirv extension specifically calls out how GLSL doesn't have these variables in its "Corresponding features not added to GLSL that GL_KHR_vulkan_glsl added" section.

**Comment by pdaniell-nv** [comment]
Thanks for the fix. Merged and closing issue.
